const img = (file) => `https://images.weserv.nl/?url=r2.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;
const tsdb = (file) => `https://images.weserv.nl/?url=www.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;

export const FORWARDS = [
    // ── ST (Strikers) — Current ──
    { id: 'haaland', name: 'Erling Haaland', country: 'Norway', club: 'Man City', rating: 94, position: 'ST', tier: 'current', image: img('bb1agj1727415216.jpg') },
    { id: 'mbappe', name: 'Kylian Mbappé', country: 'France', club: 'Real Madrid', rating: 93, position: 'ST', tier: 'current', image: tsdb('0yw04y1771265385.jpg') },
    { id: 'osimhen', name: 'Victor Osimhen', country: 'Nigeria', club: 'Galatasaray', rating: 89, position: 'ST', tier: 'current', image: img('snhzzq1702566147.jpg') },
    { id: 'kane', name: 'Harry Kane', country: 'England', club: 'Bayern', rating: 90, position: 'ST', tier: 'current', image: tsdb('0w9up71770542636.jpg') },
    { id: 'firmino', name: 'Roberto Firmino', country: 'Brazil', club: 'Al Ahli', rating: 83, position: 'ST', tier: 'current', image: img('33vciw1509999942.jpg') },
    { id: 'nunez', name: 'Darwin Núñez', country: 'Uruguay', club: 'Liverpool', rating: 83, position: 'ST', tier: 'current', image: img('6b6yhd1718090345.jpg') },
    { id: 'lukaku', name: 'Romelu Lukaku', country: 'Belgium', club: 'Napoli', rating: 84, position: 'ST', tier: 'current', image: img('0yrfdz1725016583.jpg') },
    { id: 'morata', name: 'Álvaro Morata', country: 'Spain', club: 'AC Milan', rating: 83, position: 'ST', tier: 'current', image: img('oi5xzw1565177307.jpg') },
    { id: 'dusan', name: 'Dušan Vlahović', country: 'Serbia', club: 'Juventus', rating: 85, position: 'ST', tier: 'current', image: img('m568x71546427386.jpg') },
    { id: 'fullkrug', name: 'Niclas Füllkrug', country: 'Germany', club: 'Dortmund', rating: 82, position: 'ST', tier: 'current', image: img('5uc4371722878196.jpg') },
    { id: 'gyokeres', name: 'Viktor Gyökeres', country: 'Sweden', club: 'Sporting CP', rating: 87, position: 'ST', tier: 'current', image: img('1j185h1609184069.jpg') },
    { id: 'isak', name: 'Alexander Isak', country: 'Sweden', club: 'Newcastle', rating: 86, position: 'ST', tier: 'current', image: img('b3kj061532275016.jpg') },
    { id: 'watkins', name: 'Ollie Watkins', country: 'England', club: 'Aston Villa', rating: 84, position: 'ST', tier: 'current', image: img('9l400s1752069048.jpg') },
    { id: 'benzema', name: 'Karim Benzema', country: 'France', club: 'Al Ittihad', rating: 88, position: 'ST', tier: 'current', image: img('0bzer81704623143.jpg') },
    { id: 'toney', name: 'Ivan Toney', country: 'England', club: 'Al Ahli', rating: 81, position: 'ST', tier: 'current', image: img('woevg11724686948.jpg') },
    { id: 'ferran', name: 'Ferran Torres', country: 'Spain', club: 'Barcelona', rating: 80, position: 'ST', tier: 'current', image: tsdb('wuh4nr1771253715.jpg') },
    { id: 'jackson', name: 'Nicolas Jackson', country: 'Senegal', club: 'Chelsea', rating: 81, position: 'ST', tier: 'current', image: tsdb('5bv5ob1770543405.jpg') },
    { id: 'calvert', name: 'Dominic Calvert-Lewin', country: 'England', club: 'Everton', rating: 79, position: 'ST', tier: 'current', image: img('yzn0nu1510329811.jpg') },

    // ── RW (Right Wingers) — Current ──
    { id: 'salah', name: 'Mohamed Salah', country: 'Egypt', club: 'Liverpool', rating: 91, position: 'RW', tier: 'current', image: img('o7y57t1718438615.jpg') },
    { id: 'rasheM', name: 'Marcus Rashford', country: 'England', club: 'Aston Villa', rating: 84, position: 'RW', tier: 'current', image: img('rb4hx61669799682.jpg') },
    { id: 'leao', name: 'Rafael Leão', country: 'Portugal', club: 'AC Milan', rating: 88, position: 'RW', tier: 'current', image: img('m1sh9x1549742563.jpg') },
    { id: 'vini', name: 'Vinícius Jr.', country: 'Brazil', club: 'Real Madrid', rating: 92, position: 'RW', tier: 'current', image: tsdb('lxf1he1771264845.jpg') },
    { id: 'simons', name: 'Xavi Simons', country: 'Netherlands', club: 'Leipzig', rating: 82, position: 'RW', tier: 'current', image: img('7n6vkm1628845984.jpg') },
    { id: 'diaz', name: 'Luis Díaz', country: 'Colombia', club: 'Liverpool', rating: 85, position: 'RW', tier: 'current', image: tsdb('i4s5pw1770543222.jpg') },
    { id: 'coman', name: 'Kingsley Coman', country: 'France', club: 'Bayern', rating: 83, position: 'RW', tier: 'current', image: img('axj8jq1660764566.jpg') },
    { id: 'gnabry', name: 'Serge Gnabry', country: 'Germany', club: 'Bayern', rating: 82, position: 'RW', tier: 'current', image: img('u2f5201660764673.jpg') },
    { id: 'sancho', name: 'Jadon Sancho', country: 'England', club: 'Chelsea', rating: 82, position: 'RW', tier: 'current', image: img('i1v79q1630268092.jpg') },
    { id: 'cherki', name: 'Rayan Chérki', country: 'France', club: 'Lyon', rating: 79, position: 'RW', tier: 'current', image: img('2q7f901608129152.jpg') },
    { id: 'lookman6', name: 'Ademola Lookman', country: 'Nigeria', club: 'Atalanta', rating: 84, position: 'RW', tier: 'current', image: img('y5wkl71740779922.jpg') },
    { id: 'ousmane', name: 'Ousmane Dembélé', country: 'France', club: 'PSG', rating: 86, position: 'RW', tier: 'current', image: tsdb('7h66un1770216356.jpg') },
    { id: 'chukwueze', name: 'Samuel Chukwueze', country: 'Nigeria', club: 'AC Milan', rating: 80, position: 'RW', tier: 'current', image: img('tc8syk1603550592.jpg') },

    // ── LW (Left Wingers) — Current ──
    { id: 'neymar', name: 'Neymar Jr.', country: 'Brazil', club: 'Al Hilal', rating: 87, position: 'LW', tier: 'current', image: img('j60pdx1741319053.jpg') },
    { id: 'martinelli', name: 'Gabriel Martinelli', country: 'Brazil', club: 'Arsenal', rating: 83, position: 'LW', tier: 'current', image: img('jf2gcn1716705057.jpg') },
    { id: 'chiesa', name: 'Federico Chiesa', country: 'Italy', club: 'Liverpool', rating: 82, position: 'LW', tier: 'current', image: img('o6cg3u1746376297.jpg') },
    { id: 'diallo', name: 'Amad Diallo', country: "Côte d'Ivoire", club: 'Man United', rating: 78, position: 'LW', tier: 'current', image: img('f8maua1706525745.jpg') },
    { id: 'pulisic', name: 'Christian Pulisic', country: 'USA', club: 'AC Milan', rating: 82, position: 'LW', tier: 'current', image: img('40pxda1669799830.jpg') },
    { id: 'kvara', name: 'Khvicha Kvaratskhelia', country: 'Georgia', club: 'PSG', rating: 86, position: 'LW', tier: 'current', image: tsdb('l1gq7e1770217076.jpg') },
    { id: 'antony', name: 'Antony', country: 'Brazil', club: 'Real Betis', rating: 79, position: 'LW', tier: 'current', image: img('olw7ts1653164187.jpg') },
    { id: 'madueke', name: 'Noni Madueke', country: 'England', club: 'Chelsea', rating: 79, position: 'LW', tier: 'current', image: tsdb('ndpkvb1769331026.jpg') },

    // ── LEGEND STs ──
    { id: 'messi', name: 'Lionel Messi', country: 'Argentina', club: 'Inter Miami', rating: 98, position: 'ST', tier: 'legend', image: img('kpfsvp1725295651.jpg') },
    { id: 'cr7', name: 'Cristiano Ronaldo', country: 'Portugal', club: 'Al Nassr', rating: 97, position: 'ST', tier: 'legend', image: img('bkre241600892282.jpg') },
    { id: 'shearer', name: 'Alan Shearer', country: 'England', club: 'Legend', rating: 93, position: 'ST', tier: 'legend', image: img('vhi3oq1491481687.jpg') },
    { id: 'lewa', name: 'Robert Lewandowski', country: 'Poland', club: 'Barcelona', rating: 91, position: 'ST', tier: 'legend', image: tsdb('1ogy3i1771254580.jpg') },
    { id: 'ibra', name: 'Zlatan Ibrahimović', country: 'Sweden', club: 'Legend', rating: 93, position: 'ST', tier: 'legend', image: img('rlo1p61601657280.jpg') },
    { id: 'henry', name: 'Thierry Henry', country: 'France', club: 'Legend', rating: 95, position: 'ST', tier: 'legend', image: img('vflsaf1698248867.jpg') },
    { id: 'vandernistelrooy', name: 'Ruud van Nistelrooy', country: 'Netherlands', club: 'Legend', rating: 91, position: 'ST', tier: 'legend', image: img('kimk1g1730149163.jpg') },
    { id: 'shevchenko', name: 'Andriy Shevchenko', country: 'Ukraine', club: 'Legend', rating: 92, position: 'ST', tier: 'legend', image: img('x4jrtk1638451410.jpg') },
    { id: 'batigol', name: 'Gabriel Batistuta', country: 'Argentina', club: 'Legend', rating: 92, position: 'ST', tier: 'legend', image: img('1fxkwc1528735028.jpg') },
    { id: 'torres_f', name: 'Fernando Torres', country: 'Spain', club: 'Legend', rating: 90, position: 'ST', tier: 'legend', image: img('bk5d9n1710931499.jpg') },
    { id: 'drogba', name: 'Didier Drogba', country: "Côte d'Ivoire", club: 'Legend', rating: 92, position: 'ST', tier: 'legend', image: img('o5en9h1710164866.jpg') },
    { id: 'tevez', name: 'Carlos Tévez', country: 'Argentina', club: 'Legend', rating: 89, position: 'ST', tier: 'legend', image: img('piragk1765491209.jpg') },
    { id: 'rooney', name: 'Wayne Rooney', country: 'England', club: 'Legend', rating: 90, position: 'ST', tier: 'legend', image: img('w561fs1732109007.jpg') },
    { id: 'villa', name: 'David Villa', country: 'Spain', club: 'Legend', rating: 90, position: 'ST', tier: 'legend', image: img('zgerfw1659207687.jpg') },
    { id: 'inzaghi', name: 'Filippo Inzaghi', country: 'Italy', club: 'Legend', rating: 89, position: 'ST', tier: 'legend', image: img('l1u8341578400024.jpg') },
    { id: 'suarez', name: 'Luis Suárez', country: 'Uruguay', club: 'Legend', rating: 92, position: 'ST', tier: 'legend', image: tsdb('nd8zl11770024667.jpg') },
    { id: 'totti', name: 'Francesco Totti', country: 'Italy', club: 'Legend', rating: 91, position: 'ST', tier: 'legend', image: img('qewao21537033596.jpg') },
    { id: 'morientes', name: 'Fernando Morientes', country: 'Spain', club: 'Legend', rating: 87, position: 'ST', tier: 'legend', image: img('c54ln61526728491.jpg') },
    { id: 'weah', name: 'George Weah', country: 'Liberia', club: 'Legend', rating: 90, position: 'ST', tier: 'legend', image: img('1wso0o1640301867.jpg') },
    { id: 'cantona', name: 'Eric Cantona', country: 'France', club: 'Legend', rating: 92, position: 'ST', tier: 'legend', image: img('9s9wtz1599763504.jpg') },
    { id: 'lineker', name: 'Gary Lineker', country: 'England', club: 'Legend', rating: 89, position: 'ST', tier: 'legend', image: img('xvn80x1595024932.jpg') },
    { id: 'maradona75', name: 'Diego Maradona', country: 'Argentina', club: 'Legend', rating: 99, position: 'ST', tier: 'legend', image: img('z4v3ox1515072958.jpg') },
    { id: 'cruyff', name: 'Johan Cruyff', country: 'Netherlands', club: 'Legend', rating: 97, position: 'ST', tier: 'legend', image: img('3ur2pq1546353399.jpg') },
    { id: 'klinsmann', name: 'Jürgen Klinsmann', country: 'Germany', club: 'Legend', rating: 88, position: 'ST', tier: 'legend', image: img('ei6u7g1736198426.jpg') },
    { id: 'adriano', name: 'Adriano', country: 'Brazil', club: 'Legend', rating: 90, position: 'ST', tier: 'legend', image: img('aeq7t81518288671.jpg') },
    { id: 'owen', name: 'Michael Owen', country: 'England', club: 'Legend', rating: 89, position: 'ST', tier: 'legend', image: img('9jw5051591954340.jpg') },

    // ── LEGEND RWs / LWs ──
    { id: 'figo', name: 'Luís Figo', country: 'Portugal', club: 'Legend', rating: 93, position: 'RW', tier: 'legend', image: img('dww5py1541329604.jpg') },
    { id: 'robben', name: 'Arjen Robben', country: 'Netherlands', club: 'Legend', rating: 92, position: 'RW', tier: 'legend', image: img('y6srkx1702790865.jpg') },
    { id: 'ribery', name: 'Franck Ribéry', country: 'France', club: 'Legend', rating: 92, position: 'LW', tier: 'legend', image: img('8llbi61705094475.jpg') },
    { id: 'giggs', name: 'Ryan Giggs', country: 'Wales', club: 'Legend', rating: 91, position: 'LW', tier: 'legend', image: img('i5c8fo1612098367.jpg') },
    { id: 'roberto_c', name: 'Roberto Carlos', country: 'Brazil', club: 'Legend', rating: 90, position: 'LW', tier: 'legend', image: img('u4uikp1541330867.jpg') },
    { id: 'stoichkov', name: 'Hristo Stoichkov', country: 'Bulgaria', club: 'Legend', rating: 91, position: 'LW', tier: 'legend', image: img('2t7amx1541350868.jpg') },
    { id: 'pires', name: 'Robert Pirès', country: 'France', club: 'Legend', rating: 89, position: 'LW', tier: 'legend', image: img('owa5rf1595098704.jpg') },
    { id: 'wright', name: 'Ian Wright', country: 'England', club: 'Legend', rating: 87, position: 'ST', tier: 'legend', image: img('lg5tsz1711379786.jpg') },
    { id: 'baggio', name: 'Roberto Baggio', country: 'Italy', club: 'Legend', rating: 94, position: 'ST', tier: 'legend', image: img('46dpqf1496579845.jpg') },
    { id: 'puskas', name: 'Ferenc Puskás', country: 'Hungary', club: 'Legend', rating: 97, position: 'ST', tier: 'legend', image: img('j3etee1596140507.jpg') },
    { id: 'rivaldo', name: 'Rivaldo', country: 'Brazil', club: 'Legend', rating: 94, position: 'LW', tier: 'legend', image: img('kthwz11490135768.jpg') },
    { id: 'raul', name: 'Raúl', country: 'Spain', club: 'Legend', rating: 92, position: 'ST', tier: 'legend', image: img('bk31f21541332076.jpg') },
    { id: 'hugo', name: 'Hugo Sánchez', country: 'Mexico', club: 'Legend', rating: 90, position: 'ST', tier: 'legend', image: img('nmp08u1530036189.jpg') },

    // --- NEW ADDITIONS ---
    { id: 'dusantadic', name: 'Dusan Tadic', country: 'Serbia', club: 'Fenerbahce', rating: 81, position: 'ST', tier: 'current', image: img('ceurl91558181472.jpg') },
    { id: 'antoinegriezmann', name: 'Antoine Griezmann', country: 'France', club: 'Atletico Madrid', rating: 79, position: 'ST', tier: 'current', image: img('xpmyw01702565423.jpg') },
    { id: 'joaofelix', name: 'João Félix', country: 'Portugal', club: 'Al-Nassr', rating: 88, position: 'ST', tier: 'current', image: img('b253cy1724311014.jpg') },
    { id: 'memphisdepay', name: 'Memphis Depay', country: 'The Netherlands', club: 'Corinthians', rating: 84, position: 'ST', tier: 'current', image: img('b8ce921706956738.jpg') },
    { id: 'wissambenyedder', name: 'Wissam Ben Yedder', country: 'France', club: 'Sakaryaspor', rating: 85, position: 'ST', tier: 'current', image: img('anld241597255753.jpg') },
    { id: 'ciroimmobile', name: 'Ciro Immobile', country: 'Italy', club: 'Paris FC', rating: 86, position: 'ST', tier: 'current', image: img('asqqhs1702564776.jpg') },
    { id: 'richarlison', name: 'Richarlison', country: 'Brazil', club: 'Tottenham Hotspur', rating: 86, position: 'ST', tier: 'current', image: tsdb('9c6sim1770894215.jpg') },
    { id: 'gabrieljesus', name: 'Gabriel Jesus', country: 'Brazil', club: 'Arsenal', rating: 86, position: 'ST', tier: 'current', image: img('iwt0021678196502.jpg') },
    { id: 'tammyabraham', name: 'Tammy Abraham', country: 'England', club: 'Aston Villa', rating: 81, position: 'ST', tier: 'current', image: tsdb('61g7d21770200070.jpg') },
    { id: 'rauljimenez', name: 'Raúl Jiménez', country: 'Mexico', club: 'Fulham', rating: 83, position: 'ST', tier: 'current', image: img('txxruv1454116275.jpg') },
    { id: 'andreabelotti', name: 'Andrea Belotti', country: 'Italy', club: 'Cagliari', rating: 83, position: 'ST', tier: 'current', image: img('leh49n1546358292.jpg') },
    { id: 'domenicoberardi', name: 'Domenico Berardi', country: 'Italy', club: 'Sassuolo', rating: 86, position: 'ST', tier: 'current', image: img('t8tdgc1546350168.jpg') },
    { id: 'garethbale', name: 'Gareth Bale', country: 'Wales', club: '_Retired Soccer', rating: 80, position: 'ST', tier: 'current', image: img('1kis3y1618602762.jpg') },
    { id: 'edenhazard', name: 'Eden Hazard', country: 'Belgium', club: '_Retired Soccer', rating: 79, position: 'ST', tier: 'current', image: img('m19tff1698248613.jpg') },
    { id: 'marcoreus', name: 'Marco Reus', country: 'Germany', club: 'L.A. Galaxy', rating: 87, position: 'ST', tier: 'current', image: img('9bycr31669060522.jpg') },
    { id: 'leroysane', name: 'Leroy Sane', country: 'Germany', club: 'Galatasaray', rating: 87, position: 'ST', tier: 'current', image: tsdb('y87c1d1770541955.jpg') },
    { id: 'riyadmahrez', name: 'Riyad Mahrez', country: 'Algeria', club: 'Al-Ahli Saudi FC', rating: 81, position: 'ST', tier: 'current', image: img('jwon5m1557859719.jpg') },
    { id: 'heungminson', name: 'Heung-Min Son', country: 'South Korea', club: 'Los Angeles FC', rating: 88, position: 'ST', tier: 'current', image: img('12yrco1610289677.jpg') },
    { id: 'anthonymartial', name: 'Anthony Martial', country: 'France', club: '_Free Agent Soccer', rating: 81, position: 'ST', tier: 'current', image: img('rqveof1510319041.jpg') },
    { id: 'harveybarnes', name: 'Harvey Barnes', country: 'England', club: 'Newcastle United', rating: 85, position: 'ST', tier: 'current', image: tsdb('xjidxn1770796294.jpg') },
    { id: 'wilfriedzaha', name: 'Wilfried Zaha', country: 'Ivory Coast', club: 'Charlotte FC', rating: 87, position: 'ST', tier: 'current', image: img('s724731699612798.jpg') },
    { id: 'allansaintmaximin', name: 'Allan Saint-Maximin', country: 'France', club: 'Fenerbahce', rating: 81, position: 'ST', tier: 'current', image: img('rupdim1551901902.jpg') },
    { id: 'callumhudsonodoi', name: 'Callum Hudson-Odoi', country: 'England', club: 'Nottingham Forest', rating: 87, position: 'ST', tier: 'current', image: img('f8u4ew1584870907.jpg') },
    { id: 'nicolaspepe', name: 'Nicolas Pépé', country: 'Ivory Coast', club: 'Villarreal', rating: 88, position: 'ST', tier: 'current', image: img('7ewjmz1724779988.jpg') },
    { id: 'pedroneto', name: 'Pedro Neto', country: 'Portugal', club: 'Chelsea', rating: 85, position: 'ST', tier: 'current', image: tsdb('g1325q1771427940.jpg') },
    { id: 'adamatraore', name: 'Adama Traoré', country: 'Mali', club: 'Ferencváros', rating: 82, position: 'ST', tier: 'current', image: img('4pvh8j1518272691.jpg') },
    { id: 'ansufati', name: 'Ansu Fati', country: 'Spain', club: 'Monaco', rating: 88, position: 'ST', tier: 'current', image: img('gtose41659989447.jpg') },
    { id: 'rodrygo', name: 'Rodrygo', country: 'Brazil', club: 'Real Madrid', rating: 79, position: 'ST', tier: 'current', image: tsdb('81sef31771265827.jpg') },
    { id: 'raphinha', name: 'Raphinha', country: 'Brazil', club: 'Barcelona', rating: 86, position: 'ST', tier: 'current', image: tsdb('14kuzy1771260047.jpg') },
    { id: 'diogojota', name: 'Diogo Jota', country: 'Portugal', club: '_Deceased Soccer', rating: 87, position: 'ST', tier: 'current', image: img('30nujq1751541243.jpg') },
    { id: 'dejankulusevski', name: 'Dejan Kulusevski', country: 'Sweden', club: 'Tottenham Hotspur', rating: 81, position: 'ST', tier: 'current', image: tsdb('rhwek31770893654.jpg') },
    { id: 'joaquincorrea', name: 'Joaquín Correa', country: 'Argentina', club: 'Botafogo', rating: 84, position: 'ST', tier: 'current', image: img('c4vzli1546355330.jpg') },
    { id: 'jonathandavid', name: 'Jonathan David', country: 'Canada', club: 'Juventus', rating: 88, position: 'ST', tier: 'current', image: img('hnv78h1742289489.jpg') },
    { id: 'patrikschick', name: 'Patrik Schick', country: 'Czechia', club: 'Bayer Leverkusen', rating: 86, position: 'ST', tier: 'current', image: img('5392y81578228284.jpg') },
    { id: 'codygakpo', name: 'Cody Gakpo', country: 'The Netherlands', club: 'Liverpool', rating: 80, position: 'ST', tier: 'current', image: img('m9g2ki1669145821.jpg') },
    { id: 'julianalvarez', name: 'Julián Álvarez', country: 'Argentina', club: 'Atletico Madrid', rating: 80, position: 'ST', tier: 'current', image: img('rm3tj11741979331.jpg') },
];
