const img = (file) => `https://images.weserv.nl/?url=r2.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;
const tsdb = (file) => `https://images.weserv.nl/?url=www.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;

export const DEFENDERS = [
    // ── CURRENT CBs ──
    { id: 'vvd', name: 'Virgil van Dijk', country: 'Netherlands', club: 'Liverpool', rating: 89, position: 'CB', tier: 'current', image: img('9fe0tn1720452118.jpg'), skills: ['Elite Tackling', 'Aerial Aura'] },
    { id: 'saliba', name: 'William Saliba', country: 'France', club: 'Arsenal', rating: 88, position: 'CB', tier: 'current', image: img('av91bd1724688954.jpg'), skills: ['Precision Timing', 'Rock Solid'] },
    { id: 'dias', name: 'Rúben Dias', country: 'Portugal', club: 'Man City', rating: 88, position: 'CB', tier: 'current', image: img('9kws2w1684833492.jpg'), skills: ['Leader', 'Interception'] },
    { id: 'gabriel', name: 'Gabriel Magalhães', country: 'Brazil', club: 'Arsenal', rating: 87, position: 'CB', tier: 'current', image: img('0stb4x1716706532.jpg'), skills: ['Strength', 'Set-Piece Threat'] },
    { id: 'bastoni', name: 'Alessandro Bastoni', country: 'Italy', club: 'Inter', rating: 87, position: 'CB', tier: 'current', image: img('kgodvf1602959273.jpg'), skills: ['Ball Carrier', 'Vision'] },
    { id: 'rudiger', name: 'Antonio Rüdiger', country: 'Germany', club: 'Real Madrid', rating: 87, position: 'CB', tier: 'current', image: img('o0nlgs1673465006.jpg'), skills: ['Aggressive', 'Top Speed'] },
    { id: 'araujo', name: 'Ronald Araújo', country: 'Uruguay', club: 'Barcelona', rating: 86, position: 'CB', tier: 'current', image: tsdb('z4bmo21771260643.jpg'), skills: ['Physicality', 'Wall'] },
    { id: 'romero', name: 'Cristian Romero', country: 'Argentina', club: 'Tottenham', rating: 85, position: 'CB', tier: 'current', image: tsdb('mmfst91770894655.jpg'), skills: ['Hard Tackler', 'Brave'] },
    { id: 'stones', name: 'John Stones', country: 'England', club: 'Man City', rating: 85, position: 'CB', tier: 'current', image: img('iub2p21763068622.jpg'), skills: ['Elegant', 'Passing'] },
    { id: 'militao', name: 'Éder Militão', country: 'Brazil', club: 'Real Madrid', rating: 85, position: 'CB', tier: 'current', image: tsdb('evk18a1771266122.jpg'), skills: ['Jumping', 'Recovery'] },
    { id: 'alaba', name: 'David Alaba', country: 'Austria', club: 'Real Madrid', rating: 85, position: 'CB', tier: 'current', image: img('sdcmqe1702815753.jpg'), skills: ['Versatile', 'Free-Kick'] },
    { id: 'minjae', name: 'Kim Min-jae', country: 'South Korea', club: 'Bayern', rating: 84, position: 'CB', tier: 'current', image: tsdb('heq7bc1770541689.jpg'), skills: ['Monster', 'Pace'] },
    { id: 'skriniar', name: 'Milan Škriniar', country: 'Slovakia', club: 'PSG', rating: 84, position: 'CB', tier: 'current', image: img('knn8491704623903.jpg'), skills: ['Stopper', 'Strong'] },
    { id: 'tah', name: 'Jonathan Tah', country: 'Germany', club: 'Bayern', rating: 84, position: 'CB', tier: 'current', image: tsdb('plv0km1770543333.jpg'), skills: ['Giant', 'Sprint'] },
    { id: 'gvardiol', name: 'Joško Gvardiol', country: 'Croatia', club: 'Man City', rating: 84, position: 'CB', tier: 'current', image: img('dku11k1703326585.jpg'), skills: ['Technical', 'Stamina'] },
    { id: 'marquinhos', name: 'Marquinhos', country: 'Brazil', club: 'PSG', rating: 84, position: 'CB', tier: 'current', image: tsdb('sejelk1770217582.jpg'), skills: ['Reading Play', 'Agile'] },
    { id: 'bremer', name: 'Gleison Bremer', country: 'Brazil', club: 'Juventus', rating: 84, position: 'CB', tier: 'current', image: img('icn9je1716707438.jpg'), skills: ['Man-Marking', 'Power'] },
    { id: 'konate', name: 'Ibrahima Konaté', country: 'France', club: 'Liverpool', rating: 83, position: 'CB', tier: 'current', image: img('f9phx81578228121.jpg'), skills: ['Unit', 'Speed'] },
    { id: 'martinez', name: 'Lisandro Martínez', country: 'Argentina', club: 'Man United', rating: 83, position: 'CB', tier: 'current', image: tsdb('62xrby1770994011.jpg'), skills: ['Butcher', 'Long Pass'] },
    { id: 'gimenez', name: 'José Giménez', country: 'Uruguay', club: 'Atletico', rating: 83, position: 'CB', tier: 'current', image: img('fphr8u1718082723.jpg'), skills: ['Heart', 'Aerial'] },
    { id: 'laporte', name: 'Aymeric Laporte', country: 'Spain', club: 'Al Nassr', rating: 83, position: 'CB', tier: 'current', image: img('vlenx41704364385.jpg'), skills: ['Reliable', 'Build-up'] },
    { id: 'pau-torres', name: 'Pau Torres', country: 'Spain', club: 'Aston Villa', rating: 82, position: 'CB', tier: 'current', image: tsdb('ctzs0b1770201651.jpg'), skills: ['Composure', 'Vision'] },
    { id: 'schlotterbeck', name: 'Nico Schlotterbeck', country: 'Germany', club: 'Dortmund', rating: 82, position: 'CB', tier: 'current', image: img('1sba211578088036.jpg'), skills: ['Drive', 'Pace'] },
    { id: 'akanji', name: 'Manuel Akanji', country: 'Switzerland', club: 'Man City', rating: 82, position: 'CB', tier: 'current', image: img('rkw8nb1703327216.jpg'), skills: ['Solid', 'Tactical'] },
    { id: 'ake', name: 'Nathan Aké', country: 'Netherlands', club: 'Man City', rating: 82, position: 'CB', tier: 'current', image: img('bclq8j1708244468.jpg'), skills: ['Versatile', 'Reliable'] },
    { id: 'upamecano', name: 'Dayot Upamecano', country: 'France', club: 'Bayern', rating: 82, position: 'CB', tier: 'current', image: tsdb('t53dz81770543164.jpg'), skills: ['Explosive', 'Power'] },
    { id: 'inigo', name: 'Iñigo Martínez', country: 'Spain', club: 'Barcelona', rating: 82, position: 'CB', tier: 'current', image: img('lxg7lp1574502820.jpg'), skills: ['Veteran', 'Hard'] },
    { id: 'hummels', name: 'Mats Hummels', country: 'Germany', club: 'Roma', rating: 82, position: 'CB', tier: 'current', image: img('tvbryp1717423189.jpg'), skills: ['Out-side foot', 'IQ'] },
    { id: 'tomori', name: 'Fikayo Tomori', country: 'England', club: 'AC Milan', rating: 82, position: 'CB', tier: 'current', image: img('yxwruu1469436878.jpg'), skills: ['Pace', 'Reactive'] },
    { id: 'tapsoba', name: 'Edmond Tapsoba', country: 'Burkina Faso', club: 'Leverkusen', rating: 82, position: 'CB', tier: 'current', image: img('wrgvu81585495401.jpg'), skills: ['Stable', 'Passing'] },
    { id: 'guehi', name: 'Marc Guéhi', country: 'England', club: 'Crystal Palace', rating: 82, position: 'CB', tier: 'current', image: img('wqgmpl1609183670.jpg'), skills: ['Calm', 'Timing'] },
    { id: 'pavard', name: 'Benjamin Pavard', country: 'France', club: 'Inter', rating: 82, position: 'CB', tier: 'current', image: img('36hwgb1660764260.jpg'), skills: ['Volley', 'Hybrid'] },
    { id: 'botman', name: 'Sven Botman', country: 'Netherlands', club: 'Newcastle', rating: 81, position: 'CB', tier: 'current', image: tsdb('16xv6e1770796369.jpg'), skills: ['Tall', 'Solid'] },
    { id: 'dunk', name: 'Lewis Dunk', country: 'England', club: 'Brighton', rating: 81, position: 'CB', tier: 'current', image: img('7s0ulq1510690211.jpg'), skills: ['Leader', 'Scorer'] },

    // ── CURRENT RBs ──
    { id: 'kounde', name: 'Jules Koundé', country: 'France', club: 'Barcelona', rating: 85, position: 'RB', tier: 'current', image: tsdb('0rzza71771254479.jpg'), skills: ['1v1 Defense', 'Flexible'] },
    { id: 'cancelo', name: 'João Cancelo', country: 'Portugal', club: 'Al Hilal', rating: 86, position: 'RB', tier: 'current', image: tsdb('8vj8tm1771260403.jpg'), skills: ['Playmaker', 'Crossing'] },
    { id: 'hakimi', name: 'Achraf Hakimi', country: 'Morocco', club: 'PSG', rating: 84, position: 'RB', tier: 'current', image: tsdb('lwhwh71770216476.jpg'), skills: ['Elite Pace', 'Overlap'] },
    { id: 'carvajal', name: 'Dani Carvajal', country: 'Spain', club: 'Real Madrid', rating: 84, position: 'RB', tier: 'current', image: tsdb('gapy0m1771264214.jpg'), skills: ['Warrior', 'Crossing'] },
    { id: 'walker', name: 'Kyle Walker', country: 'England', club: 'Burnley', rating: 84, position: 'RB', tier: 'current', image: img('1x2kej1557864016.jpg'), skills: ['Speedster', 'Recovery'] },
    { id: 'frimpong', name: 'Jeremie Frimpong', country: 'Netherlands', club: 'Leverkusen', rating: 84, position: 'RB', tier: 'current', image: img('4vfl5h1611865283.jpg'), skills: ['Explosive', 'Dribbling'] },
    { id: 'james', name: 'Reece James', country: 'England', club: 'Chelsea', rating: 84, position: 'RB', tier: 'current', image: img('uqrxvv1431677357.jpg'), skills: ['Strong', 'Delivery'] },
    { id: 'porro', name: 'Pedro Porro', country: 'Spain', club: 'Tottenham', rating: 83, position: 'RB', tier: 'current', image: tsdb('l9i5lo1770894141.jpg'), skills: ['Winger-like', 'Energy'] },
    { id: 'dalot', name: 'Diogo Dalot', country: 'Portugal', club: 'Man United', rating: 82, position: 'RB', tier: 'current', image: img('0rv14y1706525697.jpg'), skills: ['Modern', 'Technical'] },
    { id: 'white', name: 'Ben White', country: 'England', club: 'Arsenal', rating: 82, position: 'RB', tier: 'current', image: img('5mnqcl1628887228.jpg'), skills: ['Intelligent', 'Overlap'] },
    { id: 'trippier', name: 'Kieran Trippier', country: 'England', club: 'Newcastle', rating: 82, position: 'RB', tier: 'current', image: img('e0q0vh1663611495.jpg'), skills: ['Set-Piece', 'Curve'] },
    { id: 'mazraoui', name: 'Noussair Mazraoui', country: 'Morocco', club: 'Man United', rating: 82, position: 'RB', tier: 'current', image: tsdb('v9qusz1770994162.jpg'), skills: ['Smooth', 'Vision'] },
    { id: 'dumfries', name: 'Denzel Dumfries', country: 'Netherlands', club: 'Inter', rating: 81, position: 'RB', tier: 'current', image: img('7uz0v61544971521.jpg'), skills: ['Aerial', 'Power-Run'] },
    { id: 'gusto', name: 'Malo Gusto', country: 'France', club: 'Chelsea', rating: 80, position: 'RB', tier: 'current', image: tsdb('v2spox1771427694.jpg'), skills: ['Youthful', 'Stamina'] },
    { id: 'walker-peters', name: 'Kyle Walker-Peters', country: 'England', club: 'West Ham', rating: 78, position: 'RB', tier: 'current', image: img('i4nlij1509460143.jpg'), skills: ['Agile', 'Dribbler'] },

    // ── CURRENT LBs ──
    { id: 'davies', name: 'Alphonso Davies', country: 'Canada', club: 'Real Madrid', rating: 85, position: 'LB', tier: 'current', image: img('0p7ekk1660764614.jpg'), skills: ['Lightning', 'Recovery'] },
    { id: 'robertson', name: 'Andy Robertson', country: 'Scotland', club: 'Liverpool', rating: 85, position: 'LB', tier: 'current', image: img('mvmpbc1710165540.jpg'), skills: ['Crossing', 'Engine'] },
    { id: 'theo', name: 'Theo Hernández', country: 'France', club: 'Al Hilal', rating: 85, position: 'LB', tier: 'current', image: img('zilv2j1609512210.jpg'), skills: ['Speed-Train', 'Strike'] },
    { id: 'dimarco', name: 'Federico Dimarco', country: 'Italy', club: 'Inter', rating: 84, position: 'LB', tier: 'current', image: img('q7lkrg1546596582.jpg'), skills: ['Vision', 'Elite Cross'] },
    { id: 'mendes', name: 'Nuno Mendes', country: 'Portugal', club: 'PSG', rating: 83, position: 'LB', tier: 'current', image: tsdb('ocycug1770217690.jpg'), skills: ['Dynamic', 'Pace'] },
    { id: 'ferland-mendy', name: 'Ferland Mendy', country: 'France', club: 'Real Madrid', rating: 82, position: 'LB', tier: 'current', image: tsdb('r218wb1771266209.jpg'), skills: ['Defensive Wall', 'Strong'] },
    { id: 'udogie', name: 'Destiny Udogie', country: 'Italy', club: 'Tottenham', rating: 81, position: 'LB', tier: 'current', image: tsdb('w2l7g81770894886.jpg'), skills: ['Inside Run', 'Brave'] },
    { id: 'cucurella', name: 'Marc Cucurella', country: 'Spain', club: 'Chelsea', rating: 81, position: 'LB', tier: 'current', image: tsdb('n9f2911771426994.jpg'), skills: ['Tenacity', 'Aggressive'] },
    { id: 'calafiori', name: 'Riccardo Calafiori', country: 'Italy', club: 'Arsenal', rating: 81, position: 'LB', tier: 'current', image: tsdb('4m5wz21769332133.jpg'), skills: ['Modern CB-LB', 'Composure'] },
    { id: 'balde', name: 'Alejandro Balde', country: 'Spain', club: 'Barcelona', rating: 81, position: 'LB', tier: 'current', image: tsdb('tg8vxg1771260762.jpg'), skills: ['Agile', 'Sprint'] },
    { id: 'shaw', name: 'Luke Shaw', country: 'England', club: 'Man United', rating: 81, position: 'LB', tier: 'current', image: tsdb('wbet0c1770994226.jpg'), skills: ['Experienced', 'Crossing'] },
    { id: 'zinchenko', name: 'Oleksandr Zinchenko', country: 'Ukraine', club: 'Arsenal', rating: 80, position: 'LB', tier: 'current', image: img('g4wvkd1715902407.jpg'), skills: ['Inverted', 'Passing'] },
    { id: 'estupinan', name: 'Pervis Estupiñán', country: 'Ecuador', club: 'Brighton', rating: 80, position: 'LB', tier: 'current', image: img('vuzi4g1604867431.jpg'), skills: ['Pacey', 'Physical'] },
    { id: 'aitnouri', name: 'Rayan Aït-Nouri', country: 'Algeria', club: 'Man City', rating: 80, position: 'LB', tier: 'current', image: img('9yw7w11570031997.jpg'), skills: ['Technical', 'Dribbler'] },

    // ── LEGEND CBs ──
    { id: 'maldini', name: 'Paolo Maldini', country: 'Italy', club: 'Legend', rating: 96, position: 'CB', tier: 'legend', image: img('gmed2k1711199499.jpg'), skills: ['Absolute Wall', 'Grace'] },
    { id: 'sergio-ramos', name: 'Sergio Ramos', country: 'Spain', club: 'Legend', rating: 92, position: 'CB', tier: 'legend', image: img('4qhc7x1712489854.jpg'), skills: ['Header God', 'Clutch'] },
    { id: 'cannavaro', name: 'Fabio Cannavaro', country: 'Italy', club: 'Legend', rating: 93, position: 'CB', tier: 'legend', image: img('z2g1ey1533486611.jpg'), skills: ['Interceptor', 'Power'] },
    { id: 'thiago-silva', name: 'Thiago Silva', country: 'Brazil', club: 'Legend', rating: 90, position: 'CB', tier: 'legend', image: img('tixp6d1658771633.jpg'), skills: ['Intellect', 'Reading'] },
    { id: 'vidic', name: 'Nemanja Vidić', country: 'Serbia', club: 'Legend', rating: 90, position: 'CB', tier: 'legend', image: img('qgjqz01684833615.jpg'), skills: ['Tank', 'Aggressive'] },
    { id: 'puyol', name: 'Carles Puyol', country: 'Spain', club: 'Legend', rating: 91, position: 'CB', tier: 'legend', image: img('ids1521533491419.jpg'), skills: ['Leader', 'Braveheart'] },
    { id: 'nesta', name: 'Alessandro Nesta', country: 'Italy', club: 'Legend', rating: 93, position: 'CB', tier: 'legend', image: img('usysts1484137424.jpg'), skills: ['Slide-Tackle', 'Elite'] },

    // ── LEGEND RBs ──
    { id: 'cafu', name: 'Cafu', country: 'Brazil', club: 'Legend', rating: 93, position: 'RB', tier: 'legend', image: img('ussrws1479842265.jpg'), skills: ['Infinite Energy', 'Legend'] },
    { id: 'lahm', name: 'Philipp Lahm', country: 'Germany', club: 'Legend', rating: 93, position: 'RB', tier: 'legend', image: img('ltocxo1615114367.jpg'), skills: ['Chess-Master', 'Precise'] },
    { id: 'zanetti', name: 'Javier Zanetti', country: 'Argentina', club: 'Legend', rating: 92, position: 'RB', tier: 'legend', image: img('1ckhe11492174949.jpg'), skills: ['Consistent', 'Tractor'] },

    // ── LEGEND LBs ──
    { id: 'roberto-carlos', name: 'Roberto Carlos', country: 'Brazil', club: 'Legend', rating: 94, position: 'LB', tier: 'legend', image: img('u4uikp1541330867.jpg'), skills: ['Rocket Shot', 'Pace'] },
    { id: 'ashley-cole', name: 'Ashley Cole', country: 'England', club: 'Legend', rating: 90, position: 'LB', tier: 'legend', image: img('qoew7z1640192930.jpg'), skills: ['Defender', 'Overlap'] },
];
