const img = (file) => `https://images.weserv.nl/?url=r2.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;
const tsdb = (file) => `https://images.weserv.nl/?url=www.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;

export const GOALKEEPERS = [
    { id: 'courtois', name: 'Thibaut Courtois', country: 'Belgium', club: 'Real Madrid', rating: 90, image: tsdb('lc7dlm1771264561.jpg') },
    { id: 'alisson', name: 'Alisson Becker', country: 'Brazil', club: 'Liverpool', rating: 89, image: img('yi6dt21746034945.jpg') },
    { id: 'oblak', name: 'Jan Oblak', country: 'Slovenia', club: 'Atletico Madrid', rating: 89, image: img('tyue7b1505763846.jpg') },
    { id: 'ederson', name: 'Ederson Moraes', country: 'Brazil', club: 'Fenerbahçe', rating: 88, image: img('lqvotq1741317988.jpg') },
    { id: 'neuer', name: 'Manuel Neuer', country: 'Germany', club: 'Bayern Munich', rating: 88, image: img('uozw8z1654937382.jpg') },
    { id: 'donnarumma', name: 'Gianluigi Donnarumma', country: 'Italy', club: 'Man City', rating: 88, image: img('7kahd81704447713.jpg') },
    { id: 'ter-stegen', name: 'Marc-André ter Stegen', country: 'Germany', club: 'Barcelona', rating: 88, image: img('maz3sd1514553586.jpg') },
    { id: 'maignan', name: 'Mike Maignan', country: 'France', club: 'AC Milan', rating: 87, image: img('8owaul1735364851.jpg') },
    { id: 'martinez-gk', name: 'Emiliano Martínez', country: 'Argentina', club: 'Aston Villa', rating: 87, image: tsdb('7drp311770201331.jpg') },
    { id: 'raya', name: 'David Raya', country: 'Spain', club: 'Arsenal', rating: 86, image: img('hretja1705918045.jpg') },
    { id: 'sommer', name: 'Yann Sommer', country: 'Switzerland', club: 'Inter Milan', rating: 86, image: img('1t4z0g1702025825.jpg') },
    { id: 'kobel', name: 'Gregor Kobel', country: 'Switzerland', club: 'Dortmund', rating: 85, image: img('dl2yx01605709279.jpg') },
    { id: 'diogo-costa', name: 'Diogo Costa', country: 'Portugal', club: 'Porto', rating: 85, image: img('oosfmz1617009926.jpg') },
    { id: 'pope', name: 'Nick Pope', country: 'England', club: 'Newcastle', rating: 84, image: tsdb('kln3sy1770797142.jpg') },
    { id: 'casteels', name: 'Koen Casteels', country: 'Belgium', club: 'Al-Qadsiah', rating: 84, image: img('aynccr1578226454.jpg') },
    { id: 'lloris', name: 'Hugo Lloris', country: 'France', club: 'LAFC', rating: 84, image: img('j4e0io1670753259.jpg') },
    { id: 'onana', name: 'André Onana', country: 'Cameroon', club: 'Man United', rating: 83, image: img('5vrqyp1558201522.jpg') },
    { id: 'pickford', name: 'Jordan Pickford', country: 'England', club: 'Everton', rating: 83, image: img('lloaw31510332448.jpg') },
    { id: 'vicario', name: 'Guglielmo Vicario', country: 'Italy', club: 'Tottenham', rating: 83, image: img('evd0s01748760786.jpg') },
    { id: 'szczesny', name: 'Wojciech Szczęsny', country: 'Poland', club: 'Barcelona', rating: 82, image: img('3epoxq1713428540.jpg') },
    { id: 'navas', name: 'Keylor Navas', country: 'Costa Rica', club: 'Newell\'s Old Boys', rating: 82, image: img('lpm86z1513511831.jpg') },
    { id: 'leno', name: 'Bernd Leno', country: 'Germany', club: 'Fulham', rating: 82, image: img('shcmfk1533645517.jpg') },
    { id: 'unai-simon', name: 'Unai Simón', country: 'Spain', club: 'Athletic Bilbao', rating: 82, image: img('7mte7u1603316714.jpg') },
    { id: 'sanchez-gk', name: 'Robert Sánchez', country: 'Spain', club: 'Chelsea', rating: 81, image: tsdb('0t3h3g1771428153.jpg') },
    { id: 'flekken', name: 'Mark Flekken', country: 'Netherlands', club: 'Leverkusen', rating: 81, image: img('98he2o1578087724.jpg') },
    { id: 'mamardashvili', name: 'Giorgi Mamardashvili', country: 'Georgia', club: 'Liverpool', rating: 81, image: img('hkstyo1716611290.jpg') },
    { id: 'areola', name: 'Alphonse Areola', country: 'France', club: 'West Ham', rating: 80, image: img('dazsjl1716900961.jpg') },
    { id: 'kelleher', name: 'Caoimhín Kelleher', country: 'Ireland', club: 'Brentford', rating: 80, tier: 'current', image: img('c50sfy1585670263.jpg') },
    { id: 'lammens', name: 'Senne Lammens', country: 'Belgium', club: 'Man United', rating: 80, tier: 'current', image: img('40kl8b1623838557.jpg') },
    { id: 'k-schmeichel', name: 'Kasper Schmeichel', country: 'Denmark', club: 'Celtic', rating: 80, tier: 'current', image: img('kyitp31730845446.jpg') },
    { id: 'ramsdale', name: 'Aaron Ramsdale', country: 'England', club: 'Newcastle', rating: 79, tier: 'current', image: img('z0dple1678273036.jpg') },
    { id: 'verbruggen', name: 'Bart Verbruggen', country: 'Netherlands', club: 'Brighton', rating: 79, tier: 'current', image: img('jlon461620771748.jpg') },
    // ── LEGENDS ──
    { id: 'buffon', name: 'Gianluigi Buffon', country: 'Italy', club: 'Legend', rating: 95, tier: 'legend', image: img('cj1axe1563647999.jpg') },
    { id: 'casillas', name: 'Iker Casillas', country: 'Spain', club: 'Legend', rating: 94, tier: 'legend', image: img('ukfm1p1533286137.jpg') },
    { id: 'yashin', name: 'Lev Yashin', country: 'Russia', club: 'Legend', rating: 95, tier: 'legend', image: img('h9husk1594070133.jpg') },
    { id: 'kahn', name: 'Oliver Kahn', country: 'Germany', club: 'Legend', rating: 92, tier: 'legend', image: img('rtrwvw1479931730.jpg') },
    { id: 'p-schmeichel', name: 'Peter Schmeichel', country: 'Denmark', club: 'Legend', rating: 93, tier: 'legend', image: img('aaxz6l1711379707.jpg') },
    { id: 'van-der-sar', name: 'Edwin van der Sar', country: 'Netherlands', club: 'Legend', rating: 91, tier: 'legend', image: img('e55dw81586639436.jpg') },
    { id: 'cech', name: 'Petr Čech', country: 'Czech Republic', club: 'Legend', rating: 92, tier: 'legend', image: img('oekypo1711380149.jpg') },
    { id: 'zoff', name: 'Dino Zoff', country: 'Italy', club: 'Legend', rating: 93, tier: 'legend', image: img('0eji2v1614027928.jpg') },
    { id: 'handanovic', name: 'Samir Handanovič', country: 'Slovenia', club: 'Legend', rating: 87, tier: 'legend', image: img('vael4k1546189861.jpg') },
    { id: 'julio-cesar', name: 'Júlio César', country: 'Brazil', club: 'Legend', rating: 88, tier: 'legend', image: img('wqstrq1432667537.jpg') },
    { id: 'joe-hart', name: 'Joe Hart', country: 'England', club: 'Legend', rating: 85, tier: 'legend', image: img('owujl91713513917.jpg') },
    { id: 'tim-howard', name: 'Tim Howard', country: 'USA', club: 'Legend', rating: 85, tier: 'legend', image: img('d9jzta1709733658.jpg') },
    { id: 'claudio-bravo', name: 'Claudio Bravo', country: 'Chile', club: 'Legend', rating: 85, tier: 'legend', image: img('lim7gi1715623692.jpg') },
    { id: 'pepe-reina', name: 'Pepe Reina', country: 'Spain', club: 'Legend', rating: 85, tier: 'legend', image: img('wd0fca1533744597.jpg') },

    // --- NEW ADDITIONS ---
    { id: 'edouardmendy', name: 'Édouard Mendy', country: 'Senegal', club: 'Al-Ahli Saudi FC', rating: 79, position: 'GK', tier: 'current', image: img('op4tlc1601070063.jpg') },
    { id: 'simonmignolet', name: 'Simon Mignolet', country: 'Belgium', club: 'Club Brugge', rating: 88, position: 'GK', tier: 'current', image: img('ps20em1709733297.jpg') },
    { id: 'loriskarius', name: 'Loris Karius', country: 'Germany', club: 'Schalke 04', rating: 86, position: 'GK', tier: 'current', image: img('mrgd881548111926.jpg') },
    { id: 'kepaarrizabalaga', name: 'Kepa Arrizabalaga', country: 'Spain', club: 'Arsenal', rating: 84, position: 'GK', tier: 'current', image: tsdb('mfykkf1769332084.jpg') },
    { id: 'ruipatricio', name: 'Rui Patrício', country: 'Portugal', club: 'Al Ain', rating: 82, position: 'GK', tier: 'current', image: img('dtns5o1708025894.jpg') },
    { id: 'keylornavas', name: 'Keylor Navas', country: 'Costa Rica', club: 'Newell\'s Old Boys', rating: 79, position: 'GK', tier: 'current', image: img('lpm86z1513511831.jpg') },
    { id: 'lukashradecky', name: 'Lukas Hradecky', country: 'Finland', club: 'Monaco', rating: 79, position: 'GK', tier: 'current', image: img('7aag3g1578225981.jpg') },
    { id: 'kevintrapp', name: 'Kevin Trapp', country: 'Germany', club: 'Paris FC', rating: 86, position: 'GK', tier: 'current', image: img('3hzctu1578087311.jpg') },
    { id: 'oliverbaumann', name: 'Oliver Baumann', country: 'Germany', club: 'Hoffenheim', rating: 87, position: 'GK', tier: 'current', image: img('ba7j8e1578088931.jpg') },
    { id: 'illanmeslier', name: 'Illan Meslier', country: 'France', club: 'Leeds United', rating: 86, position: 'GK', tier: 'current', image: img('9uz8a31595086150.jpg') },
    { id: 'alexremiro', name: 'Álex Remiro', country: 'Spain', club: 'Real Sociedad', rating: 83, position: 'GK', tier: 'current', image: img('laczae1529233360.jpg') },
    { id: 'dominiklivakovic', name: 'Dominik Livaković', country: 'Croatia', club: 'Girona', rating: 82, position: 'GK', tier: 'current', image: img('c7otgv1622023476.jpg') },
    { id: 'paulopez', name: 'Pau López', country: 'Spain', club: 'Real Betis', rating: 83, position: 'GK', tier: 'current', image: img('u8tbec1724485539.jpg') },
    { id: 'alexmeret', name: 'Alex Meret', country: 'Italy', club: 'Napoli', rating: 80, position: 'GK', tier: 'current', image: tsdb('nmbcsc1771247005.jpg') },
    { id: 'wladimirofalcone', name: 'Wladimiro Falcone', country: 'Italy', club: 'Lecce', rating: 83, position: 'GK', tier: 'current', image: img('jhi1j01546085777.jpg') },
    { id: 'ivanprovedel', name: 'Ivan Provedel', country: 'Italy', club: 'Lazio', rating: 88, position: 'GK', tier: 'current', image: img('abhqpq1546699343.jpg') },
    { id: 'josesa', name: 'Mikel San Jose', country: 'Spain', club: '_Retired Soccer', rating: 83, position: 'GK', tier: 'current', image: img('hoozqh1609533940.jpg') },
    { id: 'jaspercillessen', name: 'Jasper Cillessen', country: 'The Netherlands', club: 'NEC Nijmegen', rating: 88, position: 'GK', tier: 'current', image: img('jj8mdz1546169612.jpg') },
    { id: 'justinbijlow', name: 'Justin Bijlow', country: 'The Netherlands', club: 'Feyenoord', rating: 88, position: 'GK', tier: 'current', image: img('gtz7xy1668376531.jpg') },
    { id: 'andriesnoppert', name: 'Andries Noppert', country: 'The Netherlands', club: 'SC Heerenveen', rating: 81, position: 'GK', tier: 'current', image: img('xgr4u01668376157.jpg') },
    { id: 'deanhenderson', name: 'Dean Henderson', country: 'England', club: 'Crystal Palace', rating: 85, position: 'GK', tier: 'current', image: img('bce0s81533300422.jpg') },
    { id: 'arijanetmuric', name: 'Arijanet Murić', country: 'Kosovo', club: 'Sassuolo', rating: 88, position: 'GK', tier: 'current', image: img('glc44q1658572397.jpg') },
    { id: 'jamestrafford', name: 'James Trafford', country: 'England', club: 'Manchester City', rating: 88, position: 'GK', tier: 'current', image: img('4a78dn1626203719.jpg') },
    { id: 'tomheaton', name: 'Tom Heaton', country: 'England', club: 'Manchester United', rating: 82, position: 'GK', tier: 'current', image: img('qvsjlt1713182159.jpg') },
    { id: 'martindubravka', name: 'Martin Dubravka', country: 'Slovakia', club: 'Burnley', rating: 87, position: 'GK', tier: 'current', image: img('qmtpr21569839002.jpg') },
    { id: 'karldarlow', name: 'Karl Darlow', country: 'England', club: 'Leeds United', rating: 84, position: 'GK', tier: 'current', image: img('nwgpnh1509745960.jpg') },
    { id: 'dannyward', name: 'Danny Ward', country: 'Wales', club: 'Wrexham', rating: 85, position: 'GK', tier: 'current', image: img('tz7fof1510004879.jpg') },
    { id: 'waynehennessey', name: 'Wayne Hennessey', country: 'Wales', club: '_Retired Soccer', rating: 81, position: 'GK', tier: 'current', image: img('mip3b81706117839.jpg') },
    { id: 'lukaszfabianski', name: 'Lukasz Fabianski', country: 'Poland', club: '_Free Agent Soccer', rating: 80, position: 'GK', tier: 'current', image: img('zaanrx1716901155.jpg') },
    { id: 'ruisilva', name: 'Rui Silva', country: 'Portugal', club: 'Sporting CP', rating: 85, position: 'GK', tier: 'current', image: img('2elqkh1723792779.jpg') },
    { id: 'davidospina', name: 'David Ospina', country: 'Colombia', club: 'Atlético Nacional', rating: 85, position: 'GK', tier: 'current', image: img('cgxdl91510859290.jpg') },
    { id: 'fernandomuslera', name: 'Fernando Muslera', country: 'Uruguay', club: 'Estudiantes de La Plata', rating: 87, position: 'GK', tier: 'current', image: img('ymi2401611385822.jpg') },
    { id: 'stefanortega', name: 'Stefan Ortega', country: 'Germany', club: 'Manchester City', rating: 86, position: 'GK', tier: 'current', image: img('p7i6xr1605454311.jpg') },
    { id: 'scottcarson', name: 'Scott Carson', country: 'England', club: '_Free Agent Soccer', rating: 86, position: 'GK', tier: 'current', image: img('17p9xw1506689343.jpg') },
];
