const img = (file) => `https://images.weserv.nl/?url=r2.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;
const tsdb = (file) => `https://images.weserv.nl/?url=www.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;

export const MIDFIELDERS = [
    // ── CDM (Defensive Midfielders) ──
    { id: 'rice', name: 'Declan Rice', country: 'England', club: 'Arsenal', rating: 87, position: 'CDM', tier: 'current', image: img('ty3z7g1705918131.jpg'), skills: ['Elite Tackle', 'Interceptor'] },
    { id: 'tchouameni', name: 'Aurélien Tchouaméni', country: 'France', club: 'Real Madrid', rating: 86, position: 'CDM', tier: 'current', image: tsdb('5vmfxk1771266354.jpg'), skills: ['Powerhouse', 'Anchor'] },
    { id: 'casemiro', name: 'Casemiro', country: 'Brazil', club: 'Man United', rating: 85, position: 'CDM', tier: 'current', image: img('0g0bxh1706525357.jpg'), skills: ['Rock Solid', 'Tactical'] },
    { id: 'kimmich', name: 'Joshua Kimmich', country: 'Germany', club: 'Bayern', rating: 88, position: 'CDM', tier: 'current', image: img('kzt6uo1660764439.jpg'), skills: ['Elite Pass', 'Maestro'] },
    { id: 'caicedo', name: 'Moisés Caicedo', country: 'Ecuador', club: 'Chelsea', rating: 82, position: 'CDM', tier: 'current', image: tsdb('b32gfw1771426837.jpg'), skills: ['Engine', 'Workrate'] },
    { id: 'palinha', name: 'João Palhinha', country: 'Portugal', club: 'Bayern', rating: 84, position: 'CDM', tier: 'current', image: tsdb('uqh41y1770542213.jpg'), skills: ['Destroyer', 'Aerial'] },
    { id: 'guimaraes', name: 'Bruno Guimarães', country: 'Brazil', club: 'Newcastle', rating: 85, position: 'CDM', tier: 'current', image: img('emzl1v1749155913.jpg'), skills: ['Ball Winner', 'Playmaker'] },
    { id: 'camavinga', name: 'Eduardo Camavinga', country: 'France', club: 'Real Madrid', rating: 83, position: 'CDM', tier: 'current', image: tsdb('5w5ge71771264039.jpg'), skills: ['Versatile', 'Dynamic'] },
    { id: 'kante', name: "N'Golo Kanté", country: 'France', club: 'Fenerbahçe', rating: 84, position: 'CDM', tier: 'current', image: img('ta53tz1719040070.jpg'), skills: ['Infinite Stamina', 'Quick Intercept'] },
    { id: 'bissouma', name: 'Yves Bissouma', country: 'Mali', club: 'Tottenham', rating: 80, position: 'CDM', tier: 'current', image: tsdb('98bl1p1770824104.jpg'), skills: ['Dribbler', 'Tenacious'] },
    { id: 'mcallister', name: 'Alexis Mac Allister', country: 'Argentina', club: 'Liverpool', rating: 84, position: 'CDM', tier: 'current', image: img('9n5dnd1751999911.jpg'), skills: ['Tactical', 'Creative'] },
    { id: 'ndidi', name: 'Wilfred Ndidi', country: 'Nigeria', club: 'Everton', rating: 80, position: 'CDM', tier: 'current', image: img('191fkv1510066386.jpg'), skills: ['Tackle King', 'Aerial'] },
    { id: 'amrabat', name: 'Sofyan Amrabat', country: 'Morocco', club: 'Fenerbahçe', rating: 80, position: 'CDM', tier: 'current', image: img('0q6ic11706525567.jpg'), skills: ['Power', 'Warrior'] },
    { id: 'zakaria', name: 'Denis Zakaria', country: 'Switzerland', club: 'Monaco', rating: 79, position: 'CDM', tier: 'current', image: img('cedtu81578119453.jpg'), skills: ['Physical', 'Solid'] },
    { id: 'bennacer', name: 'Ismaël Bennacer', country: 'Algeria', club: 'AC Milan', rating: 82, position: 'CDM', tier: 'current', image: img('b7e6lo1546977985.jpg'), skills: ['Metronome', 'Agile'] },
    { id: 'neves', name: 'Rúben Neves', country: 'Portugal', club: 'Al Hilal', rating: 83, position: 'CDM', tier: 'current', image: img('ac8teq1750760630.jpg'), skills: ['Long Shot', 'Vision'] },
    { id: 'goretzka', name: 'Leon Goretzka', country: 'Germany', club: 'Bayern', rating: 83, position: 'CDM', tier: 'current', image: img('ae0e511660764497.jpg'), skills: ['Physical', 'Box-to-Box'] },
    { id: 'calhanoglu', name: 'Hakan Çalhanoğlu', country: 'Turkey', club: 'Inter', rating: 85, position: 'CDM', tier: 'current', image: img('ays7ot1737352882.jpg'), skills: ['Free Kick', 'Distributor'] },
    { id: 'jorginho', name: 'Jorginho', country: 'Italy', club: 'Arsenal', rating: 80, position: 'CDM', tier: 'current', image: img('vj8b5f1678272317.jpg'), skills: ['Controller', 'Penalty'] },

    // ── CM (Central Midfielders) ──
    { id: 'bellingham', name: 'Jude Bellingham', country: 'England', club: 'Real Madrid', rating: 89, position: 'CM', tier: 'current', image: tsdb('rfg8xd1771263826.jpg'), skills: ['Generational', 'Engine'] },
    { id: 'valverde', name: 'Federico Valverde', country: 'Uruguay', club: 'Real Madrid', rating: 87, position: 'CM', tier: 'current', image: tsdb('38ndp21771266409.jpg'), skills: ['Rocket', 'High Speed'] },
    { id: 'debruyne', name: 'Kevin De Bruyne', country: 'Belgium', club: 'Napoli', rating: 90, position: 'CM', tier: 'current', image: img('yibqv71676043512.jpg'), skills: ['Elite Cross', 'Mastermind'] },
    { id: 'modric', name: 'Luka Modrić', country: 'Croatia', club: 'Real Madrid', rating: 86, position: 'CM', tier: 'current', image: img('6j40781707595475.jpg'), skills: ['Trivela', 'Legendary'] },
    { id: 'barella', name: 'Nicolò Barella', country: 'Italy', club: 'Inter', rating: 86, position: 'CM', tier: 'current', image: img('mnj6hw1546611238.jpg'), skills: ['Warrior', 'Box-to-Box'] },
    { id: 'bernardo', name: 'Bernardo Silva', country: 'Portugal', club: 'Man City', rating: 87, position: 'CM', tier: 'current', image: img('n6lcbp1557863742.jpg'), skills: ['Workrate', 'Technical'] },
    { id: 'enzo', name: 'Enzo Fernández', country: 'Argentina', club: 'Chelsea', rating: 84, position: 'CM', tier: 'current', image: tsdb('59cm7k1771427301.jpg'), skills: ['Long Ball', 'Tempo'] },
    
    { id: 'szoboszlai', name: 'Dominik Szoboszlai', country: 'Hungary', club: 'Liverpool', rating: 82, position: 'CM', tier: 'current', image: img('1tnwli1746377031.jpg'), skills: ['Power Shot', 'Deadball'] },
    { id: 'gravenberch', name: 'Ryan Gravenberch', country: 'Netherlands', club: 'Liverpool', rating: 81, position: 'CM', tier: 'current', image: img('s2jcp81603836997.jpg'), skills: ['Carrilero', 'Ball Carry'] },
    { id: 'tonali', name: 'Sandro Tonali', country: 'Italy', club: 'Newcastle', rating: 81, position: 'CM', tier: 'current', image: tsdb('fm42f81770797717.jpg'), skills: ['Anchor', 'Aggressive'] },
    { id: 'kovacic', name: 'Mateo Kovačić', country: 'Croatia', club: 'Man City', rating: 83, position: 'CM', tier: 'current', image: img('15hnid1703325850.jpg'), skills: ['Press Resist', 'Carrier'] },
    { id: 'lavia', name: 'Roméo Lavia', country: 'Belgium', club: 'Chelsea', rating: 78, position: 'CM', tier: 'current', image: tsdb('h99lm21771427872.jpg'), skills: ['Young Star', 'Calm'] },
    { id: 'mount', name: 'Mason Mount', country: 'England', club: 'Man United', rating: 80, position: 'CM', tier: 'current', image: img('ls60ix1706526080.jpg'), skills: ['Pressing', 'Deadball'] },
    { id: 'mainoo', name: 'Kobbie Mainoo', country: 'England', club: 'Man United', rating: 78, position: 'CM', tier: 'current', image: img('h66a4l1696149845.jpg'), skills: ['Composure', 'Agile'] },
    { id: 'gallagher', name: 'Conor Gallagher', country: 'England', club: 'Atletico', rating: 80, position: 'CM', tier: 'current', image: tsdb('n4fwny1770893526.jpg'), skills: ['Engine', 'Commitment'] },
    { id: 'wijnaldum', name: 'Georginio Wijnaldum', country: 'Netherlands', club: 'Al Ettifaq', rating: 80, position: 'CM', tier: 'current', image: img('ovtyxn1510004926.jpg'), skills: ['Tactical', 'Physical'] },

    // ── CAM (Attacking Midfielders) ──
    { id: 'odegaard', name: 'Martin Ødegaard', country: 'Norway', club: 'Arsenal', rating: 88, position: 'CAM', tier: 'current', image: img('ttlff21727415365.jpg'), skills: ['Technical', 'Creative'] },
    { id: 'brunoF', name: 'Bruno Fernandes', country: 'Portugal', club: 'Man United', rating: 86, position: 'CAM', tier: 'current', image: img('1kfayc1700821747.jpg'), skills: ['Final Ball', 'Stamina'] },
    { id: 'wirtz', name: 'Florian Wirtz', country: 'Germany', club: 'Leverkusen', rating: 87, position: 'CAM', tier: 'current', image: img('m1o8hn1752010521.jpg'), skills: ['Silky', 'Genius'] },
    { id: 'musiala', name: 'Jamal Musiala', country: 'Germany', club: 'Bayern', rating: 86, position: 'CAM', tier: 'current', image: tsdb('uozuxp1770542484.jpg'), skills: ['Dribbler', 'Tricky'] },
    { id: 'foden', name: 'Phil Foden', country: 'England', club: 'Man City', rating: 87, position: 'CAM', tier: 'current', image: img('19o7yc1749157221.jpg'), skills: ['Dynamic', 'Finisher'] },
    { id: 'saka', name: 'Bukayo Saka', country: 'England', club: 'Arsenal', rating: 87, position: 'CAM', tier: 'current', image: tsdb('axl31b1769332282.jpg'), skills: ['Winger-like', 'Relentless'] },
    { id: 'nkunku', name: 'Christopher Nkunku', country: 'France', club: 'Chelsea', rating: 84, position: 'CAM', tier: 'current', image: img('ytq6zu1687263442.jpg'), skills: ['Versatile', 'Slick'] },
    { id: 'maddison', name: 'James Maddison', country: 'England', club: 'Tottenham', rating: 82, position: 'CAM', tier: 'current', image: tsdb('v9h5cx1770893917.jpg'), skills: ['Magician', 'Passing'] },
    { id: 'havertz', name: 'Kai Havertz', country: 'Germany', club: 'Arsenal', rating: 83, position: 'CAM', tier: 'current', image: img('ys8rlv1702976968.jpg'), skills: ['Target Man', 'Clutch'] },
    { id: 'muller', name: 'Thomas Müller', country: 'Germany', club: 'Bayern', rating: 83, position: 'CAM', tier: 'current', image: img('rhbgrp1702750958.jpg'), skills: ['Raumdeuter', 'Leader'] },
    { id: 'dybala', name: 'Paulo Dybala', country: 'Argentina', club: 'Roma', rating: 83, position: 'CAM', tier: 'current', image: img('csf3qy1515954038.jpg'), skills: ['Left Foot', 'Star'] },
    { id: 'olmo', name: 'Dani Olmo', country: 'Spain', club: 'Barcelona', rating: 84, position: 'CAM', tier: 'current', image: tsdb('lo29ok1771254713.jpg'), skills: ['Agile', 'Sharp'] },

    // ── LEGEND CDMs ──
    { id: 'vieira', name: 'Patrick Vieira', country: 'France', club: 'Legend', rating: 92, position: 'CDM', tier: 'legend', image: img('vl1dss1711379937.jpg'), skills: ['Invincible', 'Monster'] },
    { id: 'makelele', name: 'Claude Makélélé', country: 'France', club: 'Legend', rating: 89, position: 'CDM', tier: 'legend', image: img('x2ddr71533490040.jpg'), skills: ['Original', 'Wall'] },
    { id: 'rijkaard', name: 'Frank Rijkaard', country: 'Netherlands', club: 'Legend', rating: 91, position: 'CDM', tier: 'legend', image: img('2659qt1711199842.jpg'), skills: ['Total Foot', 'Classic'] },
    { id: 'davids', name: 'Edgar Davids', country: 'Netherlands', club: 'Legend', rating: 87, position: 'CDM', tier: 'legend', image: img('ldsrby1550420610.jpg'), skills: ['Pitbull', 'Fire'] },
    { id: 'matthaus', name: 'Lothar Matthäus', country: 'Germany', club: 'Legend', rating: 93, position: 'CDM', tier: 'legend', image: img('wg4p4e1530037991.jpg'), skills: ['All-Round', 'Leader'] },

    // ── LEGEND CMs ──
    { id: 'zidane', name: 'Zinédine Zidane', country: 'France', club: 'Legend', rating: 96, position: 'CM', tier: 'legend', image: img('trvvrs1474915622.jpg'), skills: ['Iconic', 'Artist'] },
    { id: 'xavi', name: 'Xavi Hernández', country: 'Spain', club: 'Legend', rating: 94, position: 'CM', tier: 'legend', image: img('njp0um1657653161.jpg'), skills: ['Metronome', 'Genius'] },
    { id: 'iniesta', name: 'Andrés Iniesta', country: 'Spain', club: 'Legend', rating: 94, position: 'CM', tier: 'legend', image: img('qcw4eh1688646504.jpg'), skills: ['Magic', 'Clutch'] },
    { id: 'pirlo', name: 'Andrea Pirlo', country: 'Italy', club: 'Legend', rating: 92, position: 'CM', tier: 'legend', image: img('s1eujl1689493556.jpg'), skills: ['Maestro', 'Cool'] },
    { id: 'scholes', name: 'Paul Scholes', country: 'England', club: 'Legend', rating: 89, position: 'CM', tier: 'legend', image: img('e8yic11711379613.jpg'), skills: ['Long Shot', 'Passing'] },
    { id: 'gerrard', name: 'Steven Gerrard', country: 'England', club: 'Legend', rating: 91, position: 'CM', tier: 'legend', image: img('gyyytb1717083104.jpg'), skills: ['Captain', 'Power'] },
    { id: 'lampard', name: 'Frank Lampard', country: 'England', club: 'Legend', rating: 91, position: 'CM', tier: 'legend', image: img('qu60cy1718870905.jpg'), skills: ['Goalscorer', 'Record'] },
    { id: 'seedorf', name: 'Clarence Seedorf', country: 'Netherlands', club: 'Legend', rating: 89, position: 'CM', tier: 'legend', image: img('qttvpt1484137751.jpg'), skills: ['Elite Ball', 'Strong'] },
    { id: 'kroos', name: 'Toni Kroos', country: 'Germany', club: 'Legend', rating: 90, position: 'CM', tier: 'legend', image: img('y0mq231615718372.jpg'), skills: ['Sniper', 'Calm'] },
    { id: 'gullit', name: 'Ruud Gullit', country: 'Netherlands', club: 'Legend', rating: 92, position: 'CM', tier: 'legend', image: img('2gkyji1711199190.jpg'), skills: ['Complete', 'Aura'] },
    { id: 'nedved', name: 'Pavel Nedvěd', country: 'Czech Republic', club: 'Legend', rating: 90, position: 'CM', tier: 'legend', image: img('rmulwq1595106891.jpg'), skills: ['Fury', 'Engine'] },
    { id: 'beckham', name: 'David Beckham', country: 'England', club: 'Legend', rating: 89, position: 'CM', tier: 'legend', image: img('gwkk2t1586760011.jpg'), skills: ['Curver', 'Global'] },

    // ── LEGEND CAMs ──
    { id: 'ronaldinho', name: 'Ronaldinho', country: 'Brazil', club: 'Legend', rating: 95, position: 'CAM', tier: 'legend', image: img('2dyq4u1533490608.jpg'), skills: ['Pure Joy', 'Ultimate'] },
    { id: 'kaka', name: 'Kaká', country: 'Brazil', club: 'Legend', rating: 92, position: 'CAM', tier: 'legend', image: img('qb0z3x1533486834.jpg'), skills: ['Sprinting', 'Finish'] },
    { id: 'bergkamp', name: 'Dennis Bergkamp', country: 'Netherlands', club: 'Legend', rating: 91, position: 'CAM', tier: 'legend', image: img('v7i1pu1490350140.jpg'), skills: ['Touch', 'Iceman'] },
    { id: 'platini', name: 'Michel Platini', country: 'France', club: 'Legend', rating: 94, position: 'CAM', tier: 'legend', image: img('z41k381594485720.jpg'), skills: ['Maestro', 'Scorer'] },

    // --- NEW ADDITIONS ---
    { id: 'sergiobusquets', name: 'Sergio Busquets', country: 'Spain', club: 'Inter Miami', rating: 85, position: 'CM', tier: 'current', image: tsdb('oldmtf1770023441.jpg'), skills: ['Anchor', 'Intelligence'] },
    { id: 'fabinho', name: 'Fabinho', country: 'Brazil', club: 'Al Ittihad', rating: 88, position: 'CM', tier: 'current', image: img('fx3s561534001514.jpg'), skills: ['Long Leg', 'Stopping'] },
    { id: 'thiagoalcantara', name: 'Thiago Alcantara', country: 'Spain', club: '_Retired Soccer', rating: 83, position: 'CM', tier: 'current', image: img('sbdpwv1601657415.jpg'), skills: ['Slick', 'Dribbling'] },
    { id: 'marcoverratti', name: 'Marco Verratti', country: 'Italy', club: 'Al-Arabi', rating: 88, position: 'CM', tier: 'current', image: img('qpxue31704625631.jpg'), skills: ['Interceptor', 'Pass Master'] },
    { id: 'paulpogba', name: 'Paul Pogba', country: 'France', club: 'Monaco', rating: 80, position: 'CM', tier: 'current', image: img('c1jiqs1510319219.jpg'), skills: ['Power Shot', 'Showman'] },
    { id: 'isco', name: 'Isco', country: 'Spain', club: 'Real Betis', rating: 81, position: 'CM', tier: 'current', image: img('n2i3eb1713734058.jpg'), skills: ['Magical', 'Agile'] },
    { id: 'delealli', name: 'Dele Alli', country: 'England', club: '_Free Agent Soccer', rating: 79, position: 'CM', tier: 'current', image: img('rrwtvx1469442253.jpg'), skills: ['Shadow Run', 'Technical'] },
    { id: 'marcelobrozovic', name: 'Marcelo Brozović', country: 'Croatia', club: 'Al Nassr FC', rating: 81, position: 'CM', tier: 'current', image: img('khsv221577178104.jpg'), skills: ['Metronome', 'Tireless'] },
    { id: 'piotrzielinski', name: 'Piotr Zieliński', country: 'Poland', club: 'Inter Milan', rating: 85, position: 'CM', tier: 'current', image: img('4sua201533748248.jpg'), skills: ['Distributor', 'Dribbler'] },
    { id: 'thomaspartey', name: 'Thomas Partey', country: 'Ghana', club: 'Villarreal', rating: 82, position: 'CM', tier: 'current', image: img('lnsxw11705917605.jpg'), skills: ['Physical', 'Holding'] },
    { id: 'houssemaouar', name: 'Houssem Aouar', country: 'France', club: 'Al-Ittihad', rating: 88, position: 'CM', tier: 'current', image: img('pmyp5u1534013134.jpg'), skills: ['Silky', 'Creative'] },
    { id: 'arturovidal', name: 'Arturo Vidal', country: 'Chile', club: 'Colo-Colo', rating: 87, position: 'CM', tier: 'current', image: img('k9hqf21534884616.jpg'), skills: ['Warrior', 'Box-to-Box'] },
    { id: 'koke', name: 'Koke', country: 'Spain', club: 'Atletico Madrid', rating: 88, position: 'CM', tier: 'current', image: img('tk0sag1526724817.jpg'), skills: ['Maestro', 'Captain'] },
    { id: 'marcosllorente', name: 'Marcos Llorente', country: 'Spain', club: 'Atletico Madrid', rating: 85, position: 'CM', tier: 'current', image: img('v58ccl1514397460.jpg'), skills: ['Speedster', 'Versatile'] },
    { id: 'youritielemans', name: 'Youri Tielemans', country: 'Belgium', club: 'Aston Villa', rating: 80, position: 'CM', tier: 'current', image: tsdb('zymhtt1770201587.jpg'), skills: ['Long Shot', 'Vision'] },
    { id: 'jordanhenderson', name: 'Jordan Henderson', country: 'England', club: 'Brentford', rating: 84, position: 'CM', tier: 'current', image: img('4betej1705696564.jpg'), skills: ['Leader', 'Engine'] },
    { id: 'mikelmerino', name: 'Mikel Merino', country: 'Spain', club: 'Arsenal', rating: 82, position: 'CM', tier: 'current', image: tsdb('y80ndd1769332328.jpg'), skills: ['Aerial Master', 'Tackle'] },
    { id: 'sergejmilinkovicsavic', name: 'Sergej Milinkovic-Savic', country: 'Serbia', club: 'Al Hilal', rating: 84, position: 'CM', tier: 'current', image: img('iq30bq1750761696.jpg'), skills: ['Midfield Giant', 'Scorer'] },
    { id: 'renatosanches', name: 'Renato Sanches', country: 'Portugal', club: 'Benfica', rating: 84, position: 'CM', tier: 'current', image: img('oet5z41534152962.jpg'), skills: ['Power', 'Ball Carry'] },
    { id: 'emrecan', name: 'Emre Can', country: 'Germany', club: 'Borussia Dortmund', rating: 85, position: 'CM', tier: 'current', image: img('3rca6t1705094377.jpg'), skills: ['Physical', 'Anchor'] },
    { id: 'axelwitsel', name: 'Axel Witsel', country: 'Belgium', club: 'Girona', rating: 88, position: 'CM', tier: 'current', image: img('gex6yt1706956962.jpg'), skills: ['Steady', 'Experienced'] },
    { id: 'christianeriksen', name: 'Christian Eriksen', country: 'Denmark', club: 'Wolfsburg', rating: 81, position: 'CM', tier: 'current', image: img('6znljn1706525800.jpg'), skills: ['Set Piece', 'Vision'] },
    { id: 'leandroparedes', name: 'Leandro Paredes', country: 'Argentina', club: 'Boca Juniors', rating: 86, position: 'CM', tier: 'current', image: img('vt5b0f1555959873.jpg'), skills: ['Holding', 'Aggressive'] },
    { id: 'daniceballos', name: 'Daniel Ceballos', country: 'Spain', club: 'Real Madrid', rating: 88, position: 'CM', tier: 'current', image: tsdb('zfazg71771264430.jpg'), skills: ['Silky', 'Technical'] },
    { id: 'rodrigobentancur', name: 'Rodrigo Bentancur', country: 'Uruguay', club: 'Tottenham Hotspur', rating: 83, position: 'CM', tier: 'current', image: tsdb('c03fov1770823842.jpg'), skills: ['Metronome', 'Physical'] },
    { id: 'westonmckennie', name: 'Weston McKennie', country: 'United States', club: 'Juventus', rating: 85, position: 'CM', tier: 'current', image: img('k5lx3p1621545726.jpg'), skills: ['Box-to-Box', 'Aerial'] },
    { id: 'joaomoutinho', name: 'Joao Moutinho', country: 'Portugal', club: 'Braga', rating: 79, position: 'CM', tier: 'current', image: img('trdlg41534020249.jpg'), skills: ['Maestro', 'Leader'] },
    { id: 'geoffreykondogbia', name: 'Geoffrey Kondogbia', country: 'Central African Republic', club: 'Marseille', rating: 79, position: 'CM', tier: 'current', image: img('tqusqf1518270326.jpg'), skills: ['Physical', 'Ball Win'] },
    { id: 'lucastorreira', name: 'Lucas Torreira', country: 'Uruguay', club: 'Galatasaray', rating: 82, position: 'CM', tier: 'current', image: img('7zm66z1544985889.jpg'), skills: ['Aggressive', 'Snap'] },
    { id: 'granitxhaka', name: 'Granit Xhaka', country: 'Switzerland', club: 'Sunderland', rating: 86, position: 'CM', tier: 'current', image: img('xhgqbw1678275167.jpg'), skills: ['General', 'Long Ball'] },
    { id: 'fred', name: 'Freddie Woodman', country: 'England', club: 'Liverpool', rating: 87, position: 'CM', tier: 'current', image: img('jb5l201509807510.jpg'), skills: ['Active', 'Reflex'] },
    { id: 'scottmctominay', name: 'Scott McTominay', country: 'Scotland', club: 'Napoli', rating: 88, position: 'CM', tier: 'current', image: tsdb('vjfgf21771246923.jpg'), skills: ['Warrior', 'Box-to-Box'] },
    { id: 'boubacarkamara', name: 'Boubacar Kamara', country: 'France', club: 'Aston Villa', rating: 86, position: 'CM', tier: 'current', image: img('dbact81710323756.jpg'), skills: ['Technical', 'Holding'] },
    { id: 'teunkoopmeiners', name: 'Teun Koopmeiners', country: 'The Netherlands', club: 'Juventus', rating: 80, position: 'CM', tier: 'current', image: img('9rlzkj1622152930.jpg'), skills: ['Workhorse', 'Clutch'] },
    { id: 'franckkessie', name: 'Franck Kessié', country: 'Ivory Coast', club: 'Al-Ahli Saudi FC', rating: 79, position: 'CM', tier: 'current', image: img('fhj95g1659989792.jpg'), skills: ['Tank', 'Penalty'] },
    { id: 'sekofofana', name: 'Seko Fofana', country: 'Ivory Coast', club: 'Rennes', rating: 86, position: 'CM', tier: 'current', image: img('jby1d51546354375.jpg'), skills: ['Physical', 'Dynamic'] },
    { id: 'mariogotze', name: 'Mario Gotze', country: 'Germany', club: 'Eintracht Frankfurt', rating: 81, position: 'CM', tier: 'current', image: img('oppl4m1717417734.jpg'), skills: ['Slick', 'Creative'] },
    { id: 'juliandraxler', name: 'Julian Draxler', country: 'Germany', club: 'Benfica', rating: 81, position: 'CM', tier: 'current', image: img('qvrrmm1515932395.jpg'), skills: ['Classy', 'Agile'] },
    { id: 'oscar', name: 'Oscar', country: 'Brazil', club: '_Retired Soccer', rating: 86, position: 'CM', tier: 'current', image: img('u8nhuz1767960984.jpg'), skills: ['Playmaker', 'Scorer'] },
    { id: 'jamesrodriguez', name: 'James Rodríguez', country: 'Colombia', club: 'León', rating: 80, position: 'CM', tier: 'current', image: img('yvnyty1565443385.jpg'), skills: ['Left Foot', 'Magic'] },
    { id: 'ianishagi', name: 'Ianis Hagi', country: 'Romania', club: 'Alanyaspor', rating: 84, position: 'CM', tier: 'current', image: img('6cleq71591461456.jpg'), skills: ['Two-Footed', 'Slick'] },
    { id: 'lucaspaqueta', name: 'Lucas Paquetá', country: 'Brazil', club: 'Flamengo', rating: 86, position: 'CM', tier: 'current', image: img('3mg83e1716706150.jpg'), skills: ['Flair', 'Technical'] },
    { id: 'arthurmelo', name: 'Arthur Melo', country: 'Brazil', club: 'Grêmio', rating: 87, position: 'CM', tier: 'current', image: img('ldio091621544825.jpg'), skills: ['Controller', 'Agile'] },
    { id: 'harveyelliott', name: 'Harvey Elliott', country: 'England', club: 'Aston Villa', rating: 81, position: 'CM', tier: 'current', image: tsdb('leaxd51770200679.jpg'), skills: ['Young Gem', 'Creative'] },
    { id: 'curtisjones', name: 'Curtis Jones', country: 'England', club: 'Liverpool', rating: 82, position: 'CM', tier: 'current', image: img('u5fyd21577016090.jpg'), skills: ['Pressing', 'Slick'] },
    { id: 'colepalmer', name: 'Cole Palmer', country: 'England', club: 'Chelsea', rating: 88, position: 'CM', tier: 'current', image: tsdb('r7yrsa1770541322.jpg'), skills: ['Ice Cold', 'Generational'] },
    { id: 'eberechieze', name: 'Eberechi Eze', country: 'England', club: 'Arsenal', rating: 80, position: 'CM', tier: 'current', image: tsdb('teoqqw1769332174.jpg'), skills: ['Dribbler', 'Free Flow'] },
    { id: 'rodri', name: 'Rodri', country: 'Spain', club: 'Man City', rating: 91, position: 'CDM', tier: 'current', image: '', skills: ['Control', 'Positioning'] },
    { id: 'vitinha', name: 'Vitinha', country: 'Portugal', club: 'PSG', rating: 85, position: 'CM', tier: 'current', image: '', skills: ['Tempo', 'Agility'] },
    { id: 'florian_neuhaus', name: 'Florian Neuhaus', country: 'Germany', club: 'Monchengladbach', rating: 79, position: 'CM', tier: 'current', image: '', skills: ['Composure', 'Passing'] },
    { id: 'merino_spain', name: 'Mikel Merino', country: 'Spain', club: 'Arsenal', rating: 84, position: 'CM', tier: 'current', image: '', skills: ['Aerial', 'Workhorse'] },
    { id: 'joao_neves', name: 'Joao Neves', country: 'Portugal', club: 'PSG', rating: 82, position: 'CDM', tier: 'current', image: '', skills: ['Ball Win', 'Intensity'] },
    { id: 'thuram_khephren', name: 'Khephren Thuram', country: 'France', club: 'Juventus', rating: 81, position: 'CM', tier: 'current', image: '', skills: ['Stride', 'Power'] },
    { id: 'szczesny_cam', name: 'Dani Ceballos', country: 'Spain', club: 'Real Madrid', rating: 81, position: 'CAM', tier: 'current', image: '', skills: ['Press Resist', 'Creative'] },
    { id: 'xavi_simons', name: 'Xavi Simons', country: 'Netherlands', club: 'RB Leipzig', rating: 84, position: 'CAM', tier: 'current', image: '', skills: ['Dribbling', 'Final Third'] },
    { id: 'cherki', name: 'Rayan Cherki', country: 'France', club: 'Lyon', rating: 80, position: 'CAM', tier: 'current', image: '', skills: ['Flair', 'Close Control'] },
    { id: 'reijnders', name: 'Tijjani Reijnders', country: 'Netherlands', club: 'AC Milan', rating: 83, position: 'CM', tier: 'current', image: '', skills: ['Ball Carry', 'Link Play'] },
    { id: 'fermin_lopez', name: 'Fermin Lopez', country: 'Spain', club: 'Barcelona', rating: 80, position: 'CAM', tier: 'current', image: '', skills: ['Late Runs', 'Aggression'] },
    { id: 'morgan_gibbs_white', name: 'Morgan Gibbs-White', country: 'England', club: 'Nottingham Forest', rating: 82, position: 'CAM', tier: 'current', image: '', skills: ['Progression', 'Final Ball'] },
    { id: 'paqueta_westham', name: 'Lucas Paqueta', country: 'Brazil', club: 'West Ham', rating: 84, position: 'CAM', tier: 'current', image: '', skills: ['Flair', 'Press Resistance'] },
    { id: 'kobel_cm', name: 'Exequiel Palacios', country: 'Argentina', club: 'Leverkusen', rating: 82, position: 'CM', tier: 'current', image: '', skills: ['Tempo', 'Distribution'] },
    { id: 'locatelli', name: 'Manuel Locatelli', country: 'Italy', club: 'Juventus', rating: 82, position: 'CDM', tier: 'current', image: '', skills: ['Positioning', 'Passing Range'] },
    { id: 'fofana_milan', name: 'Youssouf Fofana', country: 'France', club: 'AC Milan', rating: 82, position: 'CDM', tier: 'current', image: '', skills: ['Duels', 'Recovery'] },
    { id: 'zubimendi', name: 'Martin Zubimendi', country: 'Spain', club: 'Real Sociedad', rating: 84, position: 'CDM', tier: 'current', image: '', skills: ['Reading Play', 'Tempo Control'] },
    { id: 'angussa', name: 'Andre-Frank Zambo Anguissa', country: 'Cameroon', club: 'Napoli', rating: 82, position: 'CDM', tier: 'current', image: '', skills: ['Power', 'Ball Retention'] },
    { id: 'guendouzi', name: 'Matteo Guendouzi', country: 'France', club: 'Lazio', rating: 81, position: 'CM', tier: 'current', image: '', skills: ['Work Rate', 'Transitions'] },
    { id: 'douglas_luiz', name: 'Douglas Luiz', country: 'Brazil', club: 'Juventus', rating: 85, position: 'CM', tier: 'current', image: '', skills: ['Switch Play', 'Set Pieces'] },
    { id: 'szoboszlai_cam', name: 'Dominik Szoboszlai', country: 'Hungary', club: 'Liverpool', rating: 84, position: 'CAM', tier: 'current', image: '', skills: ['Long Shots', 'Creative Runs'] },
    { id: 'maddison_cam', name: 'James Maddison', country: 'England', club: 'Tottenham', rating: 84, position: 'CAM', tier: 'current', image: '', skills: ['Through Balls', 'Dead Ball'] },
    { id: 'musah', name: 'Yunus Musah', country: 'United States', club: 'AC Milan', rating: 79, position: 'CM', tier: 'current', image: '', skills: ['Ball Carry', 'Physicality'] },
    { id: 'ugarte', name: 'Manuel Ugarte', country: 'Uruguay', club: 'Man United', rating: 83, position: 'CDM', tier: 'current', image: '', skills: ['Ball Win', 'Aggression'] },
    { id: 'matheus_nunes', name: 'Matheus Nunes', country: 'Portugal', club: 'Man City', rating: 81, position: 'CM', tier: 'current', image: '', skills: ['Drive', 'Transitions'] },
    { id: 'gundogan', name: 'Ilkay Gundogan', country: 'Germany', club: 'Barcelona', rating: 85, position: 'CM', tier: 'current', image: '', skills: ['Late Runs', 'Control'] },
    { id: 'mcginn', name: 'John McGinn', country: 'Scotland', club: 'Aston Villa', rating: 83, position: 'CM', tier: 'current', image: '', skills: ['Work Rate', 'Engine'] },
    { id: 'pape_sarr', name: 'Pape Sarr', country: 'Senegal', club: 'Tottenham', rating: 80, position: 'CM', tier: 'current', image: '', skills: ['Mobility', 'Intensity'] },
    { id: 'mkhitaryan', name: 'Henrikh Mkhitaryan', country: 'Armenia', club: 'Inter', rating: 82, position: 'CM', tier: 'current', image: '', skills: ['Intelligence', 'Pressing'] },
    { id: 'loftus_cheek', name: 'Ruben Loftus-Cheek', country: 'England', club: 'AC Milan', rating: 81, position: 'CM', tier: 'current', image: '', skills: ['Ball Carry', 'Power'] },
    { id: 'laimer', name: 'Konrad Laimer', country: 'Austria', club: 'Bayern', rating: 81, position: 'CM', tier: 'current', image: '', skills: ['Pressing', 'Stamina'] },
    { id: 'sabitzer', name: 'Marcel Sabitzer', country: 'Austria', club: 'Dortmund', rating: 82, position: 'CM', tier: 'current', image: '', skills: ['Long Shot', 'Set Pieces'] },
    { id: 'brandt', name: 'Julian Brandt', country: 'Germany', club: 'Dortmund', rating: 83, position: 'CAM', tier: 'current', image: '', skills: ['Creativity', 'Final Ball'] },
    { id: 'zaire_emery', name: 'Warren Zaire-Emery', country: 'France', club: 'PSG', rating: 82, position: 'CM', tier: 'current', image: '', skills: ['Duels', 'Maturity'] },
    { id: 'asensio', name: 'Marco Asensio', country: 'Spain', club: 'PSG', rating: 82, position: 'CAM', tier: 'current', image: '', skills: ['Left Foot', 'Finishing'] },
    { id: 'mohamed_camara', name: 'Mohamed Camara', country: 'Mali', club: 'Monaco', rating: 80, position: 'CDM', tier: 'current', image: '', skills: ['Ball Recovery', 'Energy'] },
    { id: 'golovin', name: 'Aleksandr Golovin', country: 'Russia', club: 'Monaco', rating: 82, position: 'CAM', tier: 'current', image: '', skills: ['Link Play', 'Technique'] },
    { id: 'hofmann', name: 'Jonas Hofmann', country: 'Germany', club: 'Leverkusen', rating: 81, position: 'CAM', tier: 'current', image: '', skills: ['Crossing', 'Movement'] },
    { id: 'minamino', name: 'Takumi Minamino', country: 'Japan', club: 'Monaco', rating: 80, position: 'CAM', tier: 'current', image: '', skills: ['Smart Runs', 'Pressing'] },
];
