const img = (file) => `https://images.weserv.nl/?url=r2.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;
const tsdb = (file) => `https://images.weserv.nl/?url=www.thesportsdb.com/images/media/player/thumb/${file}&w=400&h=500&fit=cover&a=top`;

export const MIDFIELDERS = [
    // ── CDM (Defensive Midfielders) ──
    { id: 'rice', name: 'Declan Rice', country: 'England', club: 'Arsenal', rating: 87, position: 'CDM', tier: 'current', image: img('ty3z7g1705918131.jpg') },
    { id: 'tchouameni', name: 'Aurélien Tchouaméni', country: 'France', club: 'Real Madrid', rating: 86, position: 'CDM', tier: 'current', image: tsdb('5vmfxk1771266354.jpg') },
    { id: 'casemiro', name: 'Casemiro', country: 'Brazil', club: 'Man United', rating: 85, position: 'CDM', tier: 'current', image: img('0g0bxh1706525357.jpg') },
    { id: 'kimmich', name: 'Joshua Kimmich', country: 'Germany', club: 'Bayern', rating: 88, position: 'CDM', tier: 'current', image: img('kzt6uo1660764439.jpg') },
    { id: 'caicedo', name: 'Moisés Caicedo', country: 'Ecuador', club: 'Chelsea', rating: 82, position: 'CDM', tier: 'current', image: tsdb('b32gfw1771426837.jpg') },
    { id: 'palinha', name: 'João Palhinha', country: 'Portugal', club: 'Bayern', rating: 84, position: 'CDM', tier: 'current', image: tsdb('uqh41y1770542213.jpg') },
    { id: 'guimaraes', name: 'Bruno Guimarães', country: 'Brazil', club: 'Newcastle', rating: 85, position: 'CDM', tier: 'current', image: img('emzl1v1749155913.jpg') },
    { id: 'camavinga', name: 'Eduardo Camavinga', country: 'France', club: 'Real Madrid', rating: 83, position: 'CDM', tier: 'current', image: tsdb('5w5ge71771264039.jpg') },
    { id: 'kante', name: "N'Golo Kanté", country: 'France', club: 'Fenerbahçe', rating: 84, position: 'CDM', tier: 'current', image: img('ta53tz1719040070.jpg') },
    { id: 'bissouma', name: 'Yves Bissouma', country: 'Mali', club: 'Tottenham', rating: 80, position: 'CDM', tier: 'current', image: tsdb('98bl1p1770824104.jpg') },
    { id: 'mcallister', name: 'Alexis Mac Allister', country: 'Argentina', club: 'Liverpool', rating: 84, position: 'CDM', tier: 'current', image: img('9n5dnd1751999911.jpg') },
    { id: 'ndidi', name: 'Wilfred Ndidi', country: 'Nigeria', club: 'Everton', rating: 80, position: 'CDM', tier: 'current', image: img('191fkv1510066386.jpg') },
    { id: 'amrabat', name: 'Sofyan Amrabat', country: 'Morocco', club: 'Fenerbahçe', rating: 80, position: 'CDM', tier: 'current', image: img('0q6ic11706525567.jpg') },
    { id: 'zakaria', name: 'Denis Zakaria', country: 'Switzerland', club: 'Monaco', rating: 79, position: 'CDM', tier: 'current', image: img('cedtu81578119453.jpg') },
    { id: 'bennacer', name: 'Ismaël Bennacer', country: 'Algeria', club: 'AC Milan', rating: 82, position: 'CDM', tier: 'current', image: img('b7e6lo1546977985.jpg') },
    { id: 'neves', name: 'Rúben Neves', country: 'Portugal', club: 'Al Hilal', rating: 83, position: 'CDM', tier: 'current', image: img('ac8teq1750760630.jpg') },
    { id: 'goretzka', name: 'Leon Goretzka', country: 'Germany', club: 'Bayern', rating: 83, position: 'CDM', tier: 'current', image: img('ae0e511660764497.jpg') },
    { id: 'calhanoglu', name: 'Hakan Çalhanoğlu', country: 'Turkey', club: 'Inter', rating: 85, position: 'CDM', tier: 'current', image: img('ays7ot1737352882.jpg') },
    { id: 'jorginho', name: 'Jorginho', country: 'Italy', club: 'Arsenal', rating: 80, position: 'CDM', tier: 'current', image: img('vj8b5f1678272317.jpg') },

    // ── CM (Central Midfielders) ──
    { id: 'bellingham', name: 'Jude Bellingham', country: 'England', club: 'Real Madrid', rating: 89, position: 'CM', tier: 'current', image: tsdb('rfg8xd1771263826.jpg') },
    { id: 'pedri', name: 'Pedri', country: 'Spain', club: 'Barcelona', rating: 87, position: 'CM', tier: 'current', image: img('vvvc1w1626791033.jpg') },
    { id: 'valverde', name: 'Federico Valverde', country: 'Uruguay', club: 'Real Madrid', rating: 87, position: 'CM', tier: 'current', image: tsdb('38ndp21771266409.jpg') },
    { id: 'debruyne', name: 'Kevin De Bruyne', country: 'Belgium', club: 'Napoli', rating: 90, position: 'CM', tier: 'current', image: img('yibqv71676043512.jpg') },
    { id: 'modric', name: 'Luka Modrić', country: 'Croatia', club: 'Real Madrid', rating: 86, position: 'CM', tier: 'current', image: img('6j40781707595475.jpg') },
    { id: 'barella', name: 'Nicolò Barella', country: 'Italy', club: 'Inter', rating: 86, position: 'CM', tier: 'current', image: img('mnj6hw1546611238.jpg') },
    { id: 'bernardo', name: 'Bernardo Silva', country: 'Portugal', club: 'Man City', rating: 87, position: 'CM', tier: 'current', image: img('n6lcbp1557863742.jpg') },
    { id: 'enzo', name: 'Enzo Fernández', country: 'Argentina', club: 'Chelsea', rating: 84, position: 'CM', tier: 'current', image: tsdb('59cm7k1771427301.jpg') },
    { id: 'gavi', name: 'Gavi', country: 'Spain', club: 'Barcelona', rating: 82, position: 'CM', tier: 'current', image: img('uvkoy51521477385.jpg') },
    { id: 'szoboszlai', name: 'Dominik Szoboszlai', country: 'Hungary', club: 'Liverpool', rating: 82, position: 'CM', tier: 'current', image: img('1tnwli1746377031.jpg') },
    { id: 'gravenberch', name: 'Ryan Gravenberch', country: 'Netherlands', club: 'Liverpool', rating: 81, position: 'CM', tier: 'current', image: img('s2jcp81603836997.jpg') },
    { id: 'tonali', name: 'Sandro Tonali', country: 'Italy', club: 'Newcastle', rating: 81, position: 'CM', tier: 'current', image: tsdb('fm42f81770797717.jpg') },
    { id: 'kovacic', name: 'Mateo Kovačić', country: 'Croatia', club: 'Man City', rating: 83, position: 'CM', tier: 'current', image: img('15hnid1703325850.jpg') },
    { id: 'lavia', name: 'Roméo Lavia', country: 'Belgium', club: 'Chelsea', rating: 78, position: 'CM', tier: 'current', image: tsdb('h99lm21771427872.jpg') },
    { id: 'mount', name: 'Mason Mount', country: 'England', club: 'Man United', rating: 80, position: 'CM', tier: 'current', image: img('ls60ix1706526080.jpg') },
    { id: 'mainoo', name: 'Kobbie Mainoo', country: 'England', club: 'Man United', rating: 78, position: 'CM', tier: 'current', image: img('h66a4l1696149845.jpg') },
    { id: 'gallagher', name: 'Conor Gallagher', country: 'England', club: 'Atletico', rating: 80, position: 'CM', tier: 'current', image: tsdb('n4fwny1770893526.jpg') },
    { id: 'wijnaldum', name: 'Georginio Wijnaldum', country: 'Netherlands', club: 'Al Ettifaq', rating: 80, position: 'CM', tier: 'current', image: img('ovtyxn1510004926.jpg') },

    // ── CAM (Attacking Midfielders) ──
    { id: 'odegaard', name: 'Martin Ødegaard', country: 'Norway', club: 'Arsenal', rating: 88, position: 'CAM', tier: 'current', image: img('ttlff21727415365.jpg') },
    { id: 'brunoF', name: 'Bruno Fernandes', country: 'Portugal', club: 'Man United', rating: 86, position: 'CAM', tier: 'current', image: img('1kfayc1700821747.jpg') },
    { id: 'wirtz', name: 'Florian Wirtz', country: 'Germany', club: 'Leverkusen', rating: 87, position: 'CAM', tier: 'current', image: img('m1o8hn1752010521.jpg') },
    { id: 'musiala', name: 'Jamal Musiala', country: 'Germany', club: 'Bayern', rating: 86, position: 'CAM', tier: 'current', image: tsdb('uozuxp1770542484.jpg') },
    { id: 'foden', name: 'Phil Foden', country: 'England', club: 'Man City', rating: 87, position: 'CAM', tier: 'current', image: img('19o7yc1749157221.jpg') },
    { id: 'saka', name: 'Bukayo Saka', country: 'England', club: 'Arsenal', rating: 87, position: 'CAM', tier: 'current', image: tsdb('axl31b1769332282.jpg') },
    { id: 'nkunku', name: 'Christopher Nkunku', country: 'France', club: 'Chelsea', rating: 84, position: 'CAM', tier: 'current', image: img('ytq6zu1687263442.jpg') },
    { id: 'maddison', name: 'James Maddison', country: 'England', club: 'Tottenham', rating: 82, position: 'CAM', tier: 'current', image: tsdb('v9h5cx1770893917.jpg') },
    { id: 'havertz', name: 'Kai Havertz', country: 'Germany', club: 'Arsenal', rating: 83, position: 'CAM', tier: 'current', image: img('ys8rlv1702976968.jpg') },
    { id: 'muller', name: 'Thomas Müller', country: 'Germany', club: 'Bayern', rating: 83, position: 'CAM', tier: 'current', image: img('rhbgrp1702750958.jpg') },
    { id: 'dybala', name: 'Paulo Dybala', country: 'Argentina', club: 'Roma', rating: 83, position: 'CAM', tier: 'current', image: img('csf3qy1515954038.jpg') },
    { id: 'olmo', name: 'Dani Olmo', country: 'Spain', club: 'Barcelona', rating: 84, position: 'CAM', tier: 'current', image: tsdb('lo29ok1771254713.jpg') },

    // ── LEGEND CDMs ──
    { id: 'vieira', name: 'Patrick Vieira', country: 'France', club: 'Legend', rating: 92, position: 'CDM', tier: 'legend', image: img('vl1dss1711379937.jpg') },
    { id: 'makelele', name: 'Claude Makélélé', country: 'France', club: 'Legend', rating: 89, position: 'CDM', tier: 'legend', image: img('x2ddr71533490040.jpg') },
    { id: 'rijkaard', name: 'Frank Rijkaard', country: 'Netherlands', club: 'Legend', rating: 91, position: 'CDM', tier: 'legend', image: img('2659qt1711199842.jpg') },
    { id: 'davids', name: 'Edgar Davids', country: 'Netherlands', club: 'Legend', rating: 87, position: 'CDM', tier: 'legend', image: img('ldsrby1550420610.jpg') },
    { id: 'matthaus', name: 'Lothar Matthäus', country: 'Germany', club: 'Legend', rating: 93, position: 'CDM', tier: 'legend', image: img('wg4p4e1530037991.jpg') },

    // ── LEGEND CMs ──
    { id: 'zidane', name: 'Zinédine Zidane', country: 'France', club: 'Legend', rating: 96, position: 'CM', tier: 'legend', image: img('trvvrs1474915622.jpg') },
    { id: 'xavi', name: 'Xavi Hernández', country: 'Spain', club: 'Legend', rating: 94, position: 'CM', tier: 'legend', image: img('njp0um1657653161.jpg') },
    { id: 'iniesta', name: 'Andrés Iniesta', country: 'Spain', club: 'Legend', rating: 94, position: 'CM', tier: 'legend', image: img('qcw4eh1688646504.jpg') },
    { id: 'pirlo', name: 'Andrea Pirlo', country: 'Italy', club: 'Legend', rating: 92, position: 'CM', tier: 'legend', image: img('s1eujl1689493556.jpg') },
    { id: 'scholes', name: 'Paul Scholes', country: 'England', club: 'Legend', rating: 89, position: 'CM', tier: 'legend', image: img('e8yic11711379613.jpg') },
    { id: 'gerrard', name: 'Steven Gerrard', country: 'England', club: 'Legend', rating: 91, position: 'CM', tier: 'legend', image: img('gyyytb1717083104.jpg') },
    { id: 'lampard', name: 'Frank Lampard', country: 'England', club: 'Legend', rating: 91, position: 'CM', tier: 'legend', image: img('qu60cy1718870905.jpg') },
    { id: 'seedorf', name: 'Clarence Seedorf', country: 'Netherlands', club: 'Legend', rating: 89, position: 'CM', tier: 'legend', image: img('qttvpt1484137751.jpg') },
    { id: 'kroos', name: 'Toni Kroos', country: 'Germany', club: 'Legend', rating: 90, position: 'CM', tier: 'legend', image: img('y0mq231615718372.jpg') },
    { id: 'gullit', name: 'Ruud Gullit', country: 'Netherlands', club: 'Legend', rating: 92, position: 'CM', tier: 'legend', image: img('2gkyji1711199190.jpg') },
    { id: 'nedved', name: 'Pavel Nedvěd', country: 'Czech Republic', club: 'Legend', rating: 90, position: 'CM', tier: 'legend', image: img('rmulwq1595106891.jpg') },
    { id: 'beckham', name: 'David Beckham', country: 'England', club: 'Legend', rating: 89, position: 'CM', tier: 'legend', image: img('gwkk2t1586760011.jpg') },

    // ── LEGEND CAMs ──
    { id: 'ronaldinho', name: 'Ronaldinho', country: 'Brazil', club: 'Legend', rating: 95, position: 'CAM', tier: 'legend', image: img('2dyq4u1533490608.jpg') },
    { id: 'kaka', name: 'Kaká', country: 'Brazil', club: 'Legend', rating: 92, position: 'CAM', tier: 'legend', image: img('qb0z3x1533486834.jpg') },
    { id: 'bergkamp', name: 'Dennis Bergkamp', country: 'Netherlands', club: 'Legend', rating: 91, position: 'CAM', tier: 'legend', image: img('v7i1pu1490350140.jpg') },
    { id: 'platini', name: 'Michel Platini', country: 'France', club: 'Legend', rating: 94, position: 'CAM', tier: 'legend', image: img('z41k381594485720.jpg') },

    // --- NEW ADDITIONS ---
    { id: 'tonikroos', name: 'Toni Kroos', country: 'Germany', club: '_Retired Soccer', rating: 85, position: 'CM', tier: 'current', image: img('y0mq231615718372.jpg') },
    { id: 'sergiobusquets', name: 'Sergio Busquets', country: 'Spain', club: 'Inter Miami', rating: 85, position: 'CM', tier: 'current', image: tsdb('oldmtf1770023441.jpg') },
    { id: 'fabinho', name: 'Fabinho', country: 'Brazil', club: 'Al Ittihad', rating: 88, position: 'CM', tier: 'current', image: img('fx3s561534001514.jpg') },
    { id: 'thiagoalcantara', name: 'Thiago Alcantara', country: 'Spain', club: '_Retired Soccer', rating: 83, position: 'CM', tier: 'current', image: img('sbdpwv1601657415.jpg') },
    { id: 'marcoverratti', name: 'Marco Verratti', country: 'Italy', club: 'Al-Arabi', rating: 88, position: 'CM', tier: 'current', image: img('qpxue31704625631.jpg') },
    { id: 'paulpogba', name: 'Paul Pogba', country: 'France', club: 'Monaco', rating: 80, position: 'CM', tier: 'current', image: img('c1jiqs1510319219.jpg') },
    { id: 'isco', name: 'Isco', country: 'Spain', club: 'Real Betis', rating: 81, position: 'CM', tier: 'current', image: img('n2i3eb1713734058.jpg') },
    { id: 'delealli', name: 'Dele Alli', country: 'England', club: '_Free Agent Soccer', rating: 79, position: 'CM', tier: 'current', image: img('rrwtvx1469442253.jpg') },
    { id: 'marcelobrozovic', name: 'Marcelo Brozović', country: 'Croatia', club: 'Al Nassr FC', rating: 81, position: 'CM', tier: 'current', image: img('khsv221577178104.jpg') },
    { id: 'piotrzielinski', name: 'Piotr Zieliński', country: 'Poland', club: 'Inter Milan', rating: 85, position: 'CM', tier: 'current', image: img('4sua201533748248.jpg') },
    { id: 'thomaspartey', name: 'Thomas Partey', country: 'Ghana', club: 'Villarreal', rating: 82, position: 'CM', tier: 'current', image: img('lnsxw11705917605.jpg') },
    { id: 'houssemaouar', name: 'Houssem Aouar', country: 'France', club: 'Al-Ittihad', rating: 88, position: 'CM', tier: 'current', image: img('pmyp5u1534013134.jpg') },
    { id: 'arturovidal', name: 'Arturo Vidal', country: 'Chile', club: 'Colo-Colo', rating: 87, position: 'CM', tier: 'current', image: img('k9hqf21534884616.jpg') },
    { id: 'koke', name: 'Koke', country: 'Spain', club: 'Atletico Madrid', rating: 88, position: 'CM', tier: 'current', image: img('tk0sag1526724817.jpg') },
    { id: 'marcosllorente', name: 'Marcos Llorente', country: 'Spain', club: 'Atletico Madrid', rating: 85, position: 'CM', tier: 'current', image: img('v58ccl1514397460.jpg') },
    { id: 'youritielemans', name: 'Youri Tielemans', country: 'Belgium', club: 'Aston Villa', rating: 80, position: 'CM', tier: 'current', image: tsdb('zymhtt1770201587.jpg') },
    { id: 'jordanhenderson', name: 'Jordan Henderson', country: 'England', club: 'Brentford', rating: 84, position: 'CM', tier: 'current', image: img('4betej1705696564.jpg') },
    { id: 'mikelmerino', name: 'Mikel Merino', country: 'Spain', club: 'Arsenal', rating: 82, position: 'CM', tier: 'current', image: tsdb('y80ndd1769332328.jpg') },
    { id: 'sergejmilinkovicsavic', name: 'Sergej Milinkovic-Savic', country: 'Serbia', club: 'Al Hilal', rating: 84, position: 'CM', tier: 'current', image: img('iq30bq1750761696.jpg') },
    { id: 'renatosanches', name: 'Renato Sanches', country: 'Portugal', club: 'Benfica', rating: 84, position: 'CM', tier: 'current', image: img('oet5z41534152962.jpg') },
    { id: 'emrecan', name: 'Emre Can', country: 'Germany', club: 'Borussia Dortmund', rating: 85, position: 'CM', tier: 'current', image: img('3rca6t1705094377.jpg') },
    { id: 'axelwitsel', name: 'Axel Witsel', country: 'Belgium', club: 'Girona', rating: 88, position: 'CM', tier: 'current', image: img('gex6yt1706956962.jpg') },
    { id: 'christianeriksen', name: 'Christian Eriksen', country: 'Denmark', club: 'Wolfsburg', rating: 81, position: 'CM', tier: 'current', image: img('6znljn1706525800.jpg') },
    { id: 'leandroparedes', name: 'Leandro Paredes', country: 'Argentina', club: 'Boca Juniors', rating: 86, position: 'CM', tier: 'current', image: img('vt5b0f1555959873.jpg') },
    { id: 'daniceballos', name: 'Daniel Ceballos', country: 'Spain', club: 'Real Madrid', rating: 88, position: 'CM', tier: 'current', image: tsdb('zfazg71771264430.jpg') },
    { id: 'rodrigobentancur', name: 'Rodrigo Bentancur', country: 'Uruguay', club: 'Tottenham Hotspur', rating: 83, position: 'CM', tier: 'current', image: tsdb('c03fov1770823842.jpg') },
    { id: 'westonmckennie', name: 'Weston McKennie', country: 'United States', club: 'Juventus', rating: 85, position: 'CM', tier: 'current', image: img('k5lx3p1621545726.jpg') },
    { id: 'joaomoutinho', name: 'Joao Moutinho', country: 'Portugal', club: 'Braga', rating: 79, position: 'CM', tier: 'current', image: img('trdlg41534020249.jpg') },
    { id: 'geoffreykondogbia', name: 'Geoffrey Kondogbia', country: 'Central African Republic', club: 'Marseille', rating: 79, position: 'CM', tier: 'current', image: img('tqusqf1518270326.jpg') },
    { id: 'lucastorreira', name: 'Lucas Torreira', country: 'Uruguay', club: 'Galatasaray', rating: 82, position: 'CM', tier: 'current', image: img('7zm66z1544985889.jpg') },
    { id: 'granitxhaka', name: 'Granit Xhaka', country: 'Switzerland', club: 'Sunderland', rating: 86, position: 'CM', tier: 'current', image: img('xhgqbw1678275167.jpg') },
    { id: 'fred', name: 'Freddie Woodman', country: 'England', club: 'Liverpool', rating: 87, position: 'CM', tier: 'current', image: img('jb5l201509807510.jpg') },
    { id: 'scottmctominay', name: 'Scott McTominay', country: 'Scotland', club: 'Napoli', rating: 88, position: 'CM', tier: 'current', image: tsdb('vjfgf21771246923.jpg') },
    { id: 'boubacarkamara', name: 'Boubacar Kamara', country: 'France', club: 'Aston Villa', rating: 86, position: 'CM', tier: 'current', image: img('dbact81710323756.jpg') },
    { id: 'teunkoopmeiners', name: 'Teun Koopmeiners', country: 'The Netherlands', club: 'Juventus', rating: 80, position: 'CM', tier: 'current', image: img('9rlzkj1622152930.jpg') },
    { id: 'franckkessie', name: 'Franck Kessié', country: 'Ivory Coast', club: 'Al-Ahli Saudi FC', rating: 79, position: 'CM', tier: 'current', image: img('fhj95g1659989792.jpg') },
    { id: 'sekofofana', name: 'Seko Fofana', country: 'Ivory Coast', club: 'Rennes', rating: 86, position: 'CM', tier: 'current', image: img('jby1d51546354375.jpg') },
    { id: 'mariogotze', name: 'Mario Gotze', country: 'Germany', club: 'Eintracht Frankfurt', rating: 81, position: 'CM', tier: 'current', image: img('oppl4m1717417734.jpg') },
    { id: 'juliandraxler', name: 'Julian Draxler', country: 'Germany', club: 'Benfica', rating: 81, position: 'CM', tier: 'current', image: img('qvrrmm1515932395.jpg') },
    { id: 'oscar', name: 'Oscar', country: 'Brazil', club: '_Retired Soccer', rating: 86, position: 'CM', tier: 'current', image: img('u8nhuz1767960984.jpg') },
    { id: 'jamesrodriguez', name: 'James Rodríguez', country: 'Colombia', club: 'León', rating: 80, position: 'CM', tier: 'current', image: img('yvnyty1565443385.jpg') },
    { id: 'ianishagi', name: 'Ianis Hagi', country: 'Romania', club: 'Alanyaspor', rating: 84, position: 'CM', tier: 'current', image: img('6cleq71591461456.jpg') },
    { id: 'lucaspaqueta', name: 'Lucas Paquetá', country: 'Brazil', club: 'Flamengo', rating: 86, position: 'CM', tier: 'current', image: img('3mg83e1716706150.jpg') },
    { id: 'arthurmelo', name: 'Arthur Melo', country: 'Brazil', club: 'Grêmio', rating: 87, position: 'CM', tier: 'current', image: img('ldio091621544825.jpg') },
    { id: 'harveyelliott', name: 'Harvey Elliott', country: 'England', club: 'Aston Villa', rating: 81, position: 'CM', tier: 'current', image: tsdb('leaxd51770200679.jpg') },
    { id: 'curtisjones', name: 'Curtis Jones', country: 'England', club: 'Liverpool', rating: 82, position: 'CM', tier: 'current', image: img('u5fyd21577016090.jpg') },
    { id: 'colepalmer', name: 'Cole Palmer', country: 'England', club: 'Chelsea', rating: 88, position: 'CM', tier: 'current', image: tsdb('r7yrsa1770541322.jpg') },
    { id: 'eberechieze', name: 'Eberechi Eze', country: 'England', club: 'Arsenal', rating: 80, position: 'CM', tier: 'current', image: tsdb('teoqqw1769332174.jpg') },
];
